
import { Doctor, Clinic, Medicine, LabTest } from './types';

export const DISTRICTS = ['Dhaka', 'Chattogram', 'Sylhet', 'Rajshahi', 'Khulna', 'Barishal', 'Rangpur', 'Mymensingh', 'Nilphamari'];

export const SPECIALTIES = [
  { id: 'medicine', name: 'Medicine', icon: '💊', bnName: 'মেডিসিন' },
  { id: 'cardiology', name: 'Cardiology', icon: '🫀', bnName: 'হৃদরোগ' },
  { id: 'neuromedicine', name: 'Neuromedicine', icon: '🧠', bnName: 'নিউরোলজি' },
  { id: 'gynecology', name: 'Gynecology', icon: '🤰', bnName: 'গাইনী' },
  { id: 'orthopedics', name: 'Orthopedics', icon: '🦴', bnName: 'হাড়-জোড়া' },
  { id: 'pediatrics', name: 'Pediatrics', icon: '👶', bnName: 'শিশু' },
  { id: 'surgery', name: 'Surgery', icon: '🔪', bnName: 'সার্জারি' },
  { id: 'urology', name: 'Urology', icon: '💧', bnName: 'ইউরোলজি' },
  { id: 'endocrinology', name: 'Endocrinology', icon: '🩸', bnName: 'ডায়াবেটিস' },
  { id: 'ent', name: 'ENT', icon: '👂', bnName: 'নাক-কান-গলা' },
  { id: 'dermatology', name: 'Dermatology', icon: '✨', bnName: 'চর্ম-যৌন' },
  { id: 'ophthalmology', name: 'Ophthalmology', icon: '👁️', bnName: 'চক্ষু' },
  { id: 'psychiatry', name: 'Psychiatry', icon: '🧘', bnName: 'মানসিক' },
  { id: 'dentistry', name: 'Dentistry', icon: '🦷', bnName: 'দন্ত' },
  { id: 'gastroenterology', name: 'Gastroenterology', icon: '🧪', bnName: 'পরিপাকতন্ত্র' },
  { id: 'kidney', name: 'Nephrology', icon: '💧', bnName: 'কিডনি' },
  { id: 'cancer', name: 'Oncology', icon: '🧬', bnName: 'ক্যান্সার' },
  { id: 'hematology', name: 'Hematology', icon: '🩸', bnName: 'রক্তরোগ' },
  { id: 'physical-medicine', name: 'Physical Medicine', icon: '🏃', bnName: 'ফিজিকেল মেডিসিন' },
];

export const DOCTORS: Doctor[] = [
  { id: 'dr-ar-monir', name: 'ডা: মোঃ মনিরুজ্জামান মনি', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), সিসিডি (বারডেম), এমএস- গাইনী এন্ড অবস | কনসালটেন্ট গাইনোকোলজিস্ট ও সার্জন, ২৫০ শয্যা জেনারেল হাসপাতাল, নীলফামারী।', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ar', 'c-madina'], schedule: 'প্রতিদিন দুপুর ০৩টা থেকে রাত ০৯টা পর্যন্ত।', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-ar-moinul', name: 'ডা. মোঃ ময়নুল হক চৌধুরী', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস- ইউরোলজি | সহকারী অধ্যাপক- ইউরোলজি বিভাগ, ন্যাশনাল ইনস্টিটিউট অব কিডনি ডিজিজ ইউরোলজি, ঢাকা।', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতি শুক্রবার দুপুর ০২টা থেকে রাত ০৮টা পর্যন্ত।', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'dr-ar-ashequr', name: 'ডা. মোঃ আশেকুর রহমান', degree: 'এমবিবিএস (ঢাকা), বিসিএস (স্বাস্থ্য), এফসিপিএস- মেডিসিন, ডি-কার্ড (কার্ডিওলজী), এমএসিপি (USA) | কনসালটেন্ট - কার্ডিওলজী, রংপুর মেডিকেল কলেজ ও হাসপাতাল, রংপুর।', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-ar', 'c-greensign'], schedule: 'প্রতি শুক্রবার সকাল ১০টা থেকে রাত ৮টা পর্যন্ত।', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'dr-ar-samiur', name: 'ডা. মোঃ সামিউর রহমান শাহ', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), সিসিডি (বারডেম), এমডি - কার্ডিওলজী, এফসিপিএস - মেডিসিন (এফপি), এমএসিপি (USA), এমএসিসি (USA) | ক্লিনিক্যাল এন্ড ইন্টারভেনশনাল কার্ডিওলজিস্ট, জাতীয় হৃদরোগ ইনস্টিটিউট ও হাসপাতাল, ঢাকা।', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতি শুক্রবার সকাল ১০টা থেকে রাত ৮টা পর্যন্ত।', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'dr-ar-rupayan', name: 'ডা. রূপায়ন দাশ', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), ডি-অর্থো (অর্থোপেডিক্স) | কনসালটেন্ট - অর্থো সার্জারী, উপজেলা স্বাস্থ্য কমপ্লেক্স, কিশোরগঞ্জ, নীলফামারী।', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতি শুক্রবার দুপুর ০২টা থেকে রাত ০৮টা পর্যন্ত।', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-ar-deb', name: 'ডা. দেব দুলাল রায়', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), সিসিডি (বারডেম), এমডি (সাইকিয়াট্রি) | বাংলাদেশ মেডিকেল বিশ্ববিদ্যালয় (সাবেক পিজি হাসপাতাল), রংপুর মেডিকেল কলেজ।', specialty: 'Psychiatry', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতি বৃহস্পতিবার বিকাল ৪টা থেকে রাত ৯টা পর্যন্ত।', availableToday: false, rating: 4.6, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'dr-ar-ruhul', name: 'ডা: মোঃ রুহুল আমিন', degree: 'সহযোগী অধ্যাপক - নিউরোলজী, রংপুর মেডিকেল কলেজ ও হাসপাতাল, রংপুর।', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতি মঙ্গলবার বিকাল ৪টা থেকে রাত ৯টা ও শুক্রবার সকাল ১০টা থেকে রাত ১১টা।', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'dr-ar-tawhid', name: 'ডা: এস.এম. তৌহিদ হাসান', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), ডিএম (এন্ডোক্রাইনোলজী এন্ড মেটাবলিজম), এডভান্সড কোর্স ইন এন্ডোক্রাইনোলজী (মায়ো ক্লিনিক-আমেরিকা)।', specialty: 'Endocrinology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতি শুক্রবার সকাল ০৯টা থেকে দুপুর ০২টা পর্যন্ত।', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'dr-ar-shamsur', name: 'ডা: মোঃ শামসুর রহমান', degree: 'সহকারী অধ্যাপক- মেডিসিন বিভাগ, ২৫০ শয্যা জেনারেল হাসপাতাল, নীলফামারী। বাত-ব্যথা, প্যারালাইসিস, স্পোর্টস মেডিসিন বিশেষজ্ঞ।', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতি রবিবার, সোমবার ও বুধবার বিকাল ০৪টা থেকে রাত ০৮টা পর্যন্ত।', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-ar-matin', name: 'ডা: মোঃ আব্দুল মতিন', degree: 'সহকারী অধ্যাপক- মেডিসিন বিভাগ, ২৫০ শয্যা জেনারেল হাসপাতাল, নীলফামারী।', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতি শনি থেকে বৃহস্পতিবার বিকাল ০৪টা থেকে রাত ০৯টা পর্যন্ত।', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-ar-awal', name: 'ডা: মোঃ আব্দুল আউয়াল', degree: 'এমবিবিএস (ঢাকা), বিসিএস (স্বাস্থ্য), ডিসিএইচ (শিশু), বিএসএমএমইউ। নবজাতক ও শিশু বিশেষজ্ঞ (কনসালটেন্ট, শিশু)।', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'সময় জানতে কল করুন', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- ইবাদত হাসপাতাল ---
  { id: 'dr-eb-koushik', name: 'ডাঃ কৌশিক রায়', degree: 'এমবিবিএস | নবজাতক, শিশু ও কিশোর রোগ বিশেষজ্ঞ। এক্স কনসালটেন্ট (শিশু বিকাশ কেন্দ্র)।', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শনি থেকে বৃহস্পতিবার (দুপুর ৩টা - রাত ৮টা)', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-eb-tuli', name: 'ডাঃ সুলতানা নাসেরী তুলি', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (গাইনী এন্ড অবস্)। প্রসূতি, স্ত্রীরোগ বিশেষজ্ঞ ও সার্জন।', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শনি থেকে বৃহস্পতিবার (দুপুর ৩:৩০ - রাত ১০টা)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-eb-mezba', name: 'ডাঃ মেজবাহুল মোকাররাবীন (মেজবা)', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এমএস (ইউরোলজি)। ইউরোলজি বিশেষজ্ঞ ও কিডনি সার্জন।', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'মঙ্গলবার: ৩:০০ PM – ৮:০০ PM, প্রতি শুক্রবার (বিকাল ৪টা - রাত ১০টা)', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'dr-eb-munira', name: 'ডাঃ মুনিরা ফেরদৌস', degree: 'এমবিবিএস, ডিডিভি, সিসিডি (বারডেম), ডিএফবি। চর্ম ও শিশুচর্ম রোগ বিশেষজ্ঞ।', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতি শুক্রবার (সকাল ১০টা - বিকাল ৪টা)', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'dr-eb-rezaul', name: 'ডাঃ রেজাউল হক', degree: 'এমবিবিএস, এডভান্সড কোর্স ইন ডায়াবেটোলজি (ইউএসএ)। মেডিসিন, ডায়াবেটিস বিশেষজ্ঞ।', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতি শুক্রবার (সকাল ১০টা - রাত ১০টা)', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-eb-firoz', name: 'ডাঃ মো: ফিরোজ কবীর', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), পিজিটি (মেডিসিন) | মেডিসিন বিশেষজ্ঞ।', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতিদিন: ৩:০০ PM – ৮:০০ PM', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-eb-sakura', name: 'ডাঃ শাকেরা আক্তার (সাকু)', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (গাইনী এন্ড অবস্)। প্রসূতি ও গাইনী বিশেষজ্ঞ।', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতি শুক্রবার (সকাল ১০টা - রাত ১০টা)', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-eb-sohel', name: 'ডাঃ সোহেলুর রহমান সোহেল', degree: 'এমবিবিএস, ডি-অর্থো সার্জারী | হাড় ভাঙা, বাত ও ব্যথা বিশেষজ্ঞ।', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতিদিন ২:০০ PM – ৯:০০ PM (শুক্রবার বন্ধ)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'dr-eb-rouf', name: 'ডাঃ মোঃ মোস্তফা কামাল রউফ', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (মেডিসিন) | মেডিসিন ও হৃদরোগ বিশেষজ্ঞ।', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'মঙ্গল: ৩:০০ PM – ১০:০০ PM, বুধ: ৩:০০ PM – ৬:০০ PM', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },

  // --- মৌন জেনারেল হাসপাতাল ---
  { id: 'dr-moun-shankar', name: 'ডাঃ শঙ্কর কুমার সাহা', degree: 'এমবিবিএস, ডি-কার্ড (বিএসএমএমইউ)। হৃদরোগ ও মেডিসিন বিশেষজ্ঞ। সিনিয়র কনসালটেন্ট (অবঃ)।', specialty: 'cardiology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'প্রতি সোমবার (বিকাল ৩টা - রাত ৮টা) এবং প্রতি শুক্রবার (সকাল ১১টা - বিকাল ৫টা)', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'dr-moun-lopa', name: 'ডাঃ মাহফুজা আক্তার (লোপা)', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এমএস (গাইনী এন্ড অবস্)। প্রসূতি ও স্ত্রীরোগ বিশেষজ্ঞ ও সার্জন।', specialty: 'gynecology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'প্রতি শুক্রবার (সকাল ১০টা - রাত ৮টা)', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- প্যাসিফিক ল্যাবজোন ---
  { id: 'dr-pac-hafizul', name: 'ডা. মো. হাফিজুল ইসলাম', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস-গ্যাস্ট্রোএন্টারোলজি। বিশেষজ্ঞ: গ্যাস্ট্রোলিভার, মেডিসিন ও ডায়াবেটিস।', specialty: 'gastroenterology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি বৃহস্পতিবার (বিকাল ৩টা থেকে রাত ৯টা পর্যন্ত)।', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'dr-pac-ali', name: 'ডা. সৈয়দ হাসান আলী', degree: 'এমবিবিএস, ডি-অর্থো। হাড়-জোড়া, বাত-ব্যথা অর্থোপেডিক বিশেষজ্ঞ ও ট্রমা সার্জন।', specialty: 'orthopedics', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি শুক্রবার (সকাল ৯টা থেকে রাত ১০টা পর্যন্ত)।', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'dr-pac-shahjada', name: 'ডা. মো. শাহজাদা মিয়া', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এমসিপিএস (মেডিসিন)। ডায়াবেটিস ও মেডিসিন বিশেষজ্ঞ।', specialty: 'medicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি শুক্রবার (সকাল ১০টা - রাত ৮টা) ও রবিবার (বিকাল ৫টা - ৮টা)', availableToday: false, rating: 4.6, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-pac-alamin', name: 'ডা. আল-আমিন হোসেন', degree: 'এমবিবিএস, এফসিপিএস (ইন্টারনাল মেডিসিন)। বিশেষজ্ঞ: মেডিসিন, নিউরোমেডিসিন, ডায়াবেটিস।', specialty: 'neuromedicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি সোমবার ও বৃহস্পতিবার (সকাল ১০টা থেকে বিকাল ৪টা)।', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-pac-sabuj', name: 'ডা. মো. আবু তাহের সবুজ', degree: 'এমবিবিএস (ডি.জে.এম.সি)। মেডিসিন, ডায়াবেটিস এন্ড জেনারেল প্রাকটিশনার।', specialty: 'medicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি শনিবার (৯:৩০ - বিকাল ৫টা) ও মঙ্গলবার (বিকাল ৫টা - ৮টা)', availableToday: false, rating: 4.5, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'dr-pac-sarwar', name: 'ডা. মো. সারোয়ার হোসেন', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য)। হাড়-জোড়া, বাত-ব্যথা ও অর্থোপেডিক চিকিৎসক।', specialty: 'orthopedics', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন (দুপুর ২টা থেকে রাত ৯টা পর্যন্ত)।', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'dr-pac-robiul', name: 'ডা. মো. রবিউল ইসলাম', degree: 'এমবিবিএস, এমডি (মেডিসিন)। মেডিসিন, নিউরোমেডিসিন ও বক্ষব্যাধি বিশেষজ্ঞ।', specialty: 'neuromedicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি বুধবার (দুপুর ২টা থেকে রাত ৮টা পর্যন্ত)।', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'dr-pac-altaf', name: 'ডা: মো: আলতাফ হোসেন সরকার', degree: 'এমবিবিএস, এমসিপিএম, ডিপিএম। অধ্যাপক মানসিক ব্যাধি বিভাগ।', specialty: 'psychiatry', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'বৃহস্পতিবার সকাল ১০টা থেকে বিকাল ৩টা পর্যন্ত।', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'dr-pac-kayes', name: 'ডা: মো: ইমরুল কায়েস', degree: 'এমবিবিএস, পিজিটি (অর্থোপেডিক)। হাড়-জোড়া ও অর্থোপেডিক বিশেষজ্ঞ।', specialty: 'orthopedics', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি সোমবার ও বৃহস্পতিবার সকাল ১০টা থেকে বিকাল ৪টা।', availableToday: false, rating: 4.6, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'dr-pac-ayesha', name: 'ডা. আয়েশা সিদ্দিকা', degree: 'এমবিবিএস, ডিএমইউ (আল্ট্রা)। আল্ট্রাসনোলজি বিশেষজ্ঞ।', specialty: 'gynecology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'শনিবার ৯:৩০ - বিকাল ৫টা ও বুধ বিকাল ৫টা - ৮টা', availableToday: false, rating: 4.5, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'dr-pac-selimuzzaman', name: 'ডা: মোঃ সেলিমুজ্জামান', degree: 'এমবিবিএস, এমসিপিএস, এমডি রেসিডেন্ট (কার্ডিওলজি)। মেডিসিন ও হৃদরোগ বিশেষজ্ঞ।', specialty: 'cardiology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'বৃহস্পতি বিকাল ৫টা - ৯টা, শুক্র সকাল ৯টা - ৮টা', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },

  // --- Roots Eye Operation & Consultation Center ---
  { id: 'roots-eye1', name: 'Dr. Md. Mizanur Rahman', degree: 'MBBS, MS (Ophthalmology), BCS (Health) | সহযোগী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Ophthalmology', districts: ['Nilphamari'], clinics: ['c-roots'], schedule: 'সময়: (যোগাযোগ করুন)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'roots-eye2', name: 'Dr. Md. Kamrul Hasan', degree: 'MBBS (Rajshahi), BCS (Health), MS (Ophthalmology) | কনসালটেন্ট, ২৫০ শয্যা হাসপাতাল', specialty: 'Ophthalmology', districts: ['Nilphamari'], clinics: ['c-roots'], schedule: 'সময়: (যোগাযোগ করুন)', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },

  // --- Ebadot Hospital (New) ---
  { id: 'eb-sohel', name: 'Dr. Md. Sohelur Rahman Sohel', degree: 'MBBS (Rangpur Medical), D-Ortho Surgery, PRP Therapy & Ilizarov Fellowship, AO Trauma & APOA Member | হাড় ভাঙা, বাত ও ব্যথা বিশেষজ্ঞ', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতিদিন ২:০০ PM – ৯:০০ PM (শুক্রবার বন্ধ)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'eb-koushik', name: 'Dr. Koushik Roy', degree: 'MBBS | নবজাতক, শিশু ও কিশোর রোগ বিশেষজ্ঞ', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'যোগাযোগ করুন', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'eb-tuli', name: 'Dr. Sultana Nasera Tuli', degree: 'MBBS, BCS (Health), FCPS (Gynae & Obs) | Registrar, ২৫০ শয্যা জেনারেল হাসপাতাল, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শনি – বৃহস্পতি: ৩:৩০ PM – ১০:০০ PM', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'eb-riyasad', name: 'Dr. Md. Riyasad Mahabub', degree: 'MBBS, BCS (Health), CCD (BIRDEM), PGT (Medicine), DTCD (Chest Diseases) | বক্ষব্যাধি, অ্যাজমা ও ডায়াবেটিস বিশেষজ্ঞ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শনি ও সোম: ৩:৩০ PM – ৯:০০ PM', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'eb-rouf', name: 'Dr. Md. Mostafa Kamal Rouf', degree: 'MBBS, BCS (Health), FCPS (Medicine), Post Graduate Training (Neurology & Cardiology) | সহযোগী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'মঙ্গল: ৩:০০ PM – ১০:০০ PM, বুধ: ৩:০০ PM – ৬:০০ PM', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'eb-mahbub', name: 'Dr. Md. Mahabub-ul-Alam', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM) | প্রভাষক, নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শনি – বুধ: ৩:০০ PM – ৯:০০ PM', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'eb-mezbah', name: 'Dr. Mezbahul Mukarrabin Mezba', degree: 'MBBS, BCS (Health), MS (Urology), Advanced Training (Australia) | ইউরোলজি বিশেষজ্ঞ', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'মঙ্গলবার: ৩:০০ PM – ৮:০০ PM', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'eb-rony', name: 'Dr. Md. Zillur Hassan Rony', degree: 'MBBS, BCS (Health), MS (Orthopedics) – NITOR, FACS (USA), AO Training | অর্থোপেডিক বিশেষজ্ঞ ও সার্জন', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শুক্রবার: ১০:০০ AM – ৭:০০ PM', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'eb-munira', name: 'Dr. Munira Ferdous', degree: 'MBBS, DDV, CCD (BIRDEM), Fellowship in Dermatosurgery & Aesthetic Dermatology | চর্ম, যৌন ও সৌন্দর্য বিশেষজ্ঞ', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শুক্রবার: ১০:০০ AM – ৪:০০ PM', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'eb-firoz', name: 'Dr. Md. Firoz Kabir', degree: 'MBBS, BCS (Health), PGT (Medicine) | মেডিসিন বিশেষজ্ঞ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতিদিন: ৩:০০ PM – ৮:০০ PM', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'eb-saiful', name: 'Dr. Md. Saiful Islam', degree: 'MBBS (SMC), MCPS (Surgery), FCPS (Surgery) | সার্জারি বিশেষজ্ঞ ও সার্জন', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শনি - বৃহস্পতি: ৪:০০ PM – ৯:০০ PM', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'eb-narayan', name: 'Dr. Narayan Chandra Das', degree: 'MBBS, D-Ortho | হাড়-জোড়া, বাত ও ব্যথা বিশেষজ্ঞ', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শুক্রবার: ৯:০০ AM – ২:০০ PM', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'eb-sobur', name: 'Dr. Md. Abdus Sobur', degree: 'MBBS, BCS (Health), MD (Medicine) | মেডিসিন বিশেষজ্ঞ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতিদিন: ৪:০০ PM – ৯:০০ PM', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'moun-gyn1', name: 'Dr. Mst. Nasrin Akhter', degree: 'MBBS, BCS (Health), FCPS (Gynae & Obs) | গাইনী বিশেষজ্ঞ ও সার্জন', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'প্রতিদিন: ৩:০০ PM - ৭:০০ PM', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'moun-gyn2', name: 'Dr. Mahfuza Akter (Lopa)', degree: 'MBBS, BCS (Health), MS (Gynae & Obs) | কনসালটেন্ট, রংপুর মেডিকেল', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'moun-sur1', name: 'Dr. Mohammad Wajibullah', degree: 'MBBS, BCS, MRCS, MS (Colorectal Surgery) | সহকারী অধ্যাপক', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'শুক্রবার: সকাল ১১:০০ - বিকাল ৪:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'moun-card1', name: 'Dr. Shankar Kumar Saha', degree: 'MBBS, D-CARD | সিনিয়র কনসালটেন্ট', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'সোমবার: ৩:০০ - ৮:০০, শুক্রবার: ১১:০০ - ৪:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'moun-ent1', name: 'Dr. Md. Rafiqul Islam', degree: 'MBBS, DLO | ইএনটি বিশেষজ্ঞ', specialty: 'ENT', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৮:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Janata Clinic & Diagnostic Center ---
  { id: 'j-gyn1', name: 'Dr. Parul Rani Roy', degree: 'MBBS, DGO (Dhaka), FCPS (LP), Gynae & Obs | Ex-Consultant Labaid', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-sur1', name: 'Dr. M.A. Sujon', degree: 'MBBS (Raj), BCS (Health), CMU, PGT (Surgery) | মেডিকেল অফিসার, নীলফামারী মেডিকেল কলেজ', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'j-gyn3', name: 'Dr. Farzana Akter', degree: 'MBBS, BCS (Health), CMU, DMU | মেডিকেল অফিসার, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-sur2', name: 'Dr. Md. Sohrab Hossain', degree: 'MBBS, FCPS (সার্জারী) জেনারেল ও ল্যাপারোস্কপিক সার্জন | সহকারী অধ্যাপক নীলফামারী মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০ (শুক্রবার বন্ধ)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'j-kid1', name: 'Dr. Nihar Ranjan Chowdhury', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM) | মেডিকেল অফিসার, ২৫০ শয্যা হাসপাতাল, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: দুপুর ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-med-t1', name: 'Dr. Md. Masud Parvez', degree: 'MBBS (SSMC), BCS (Health), MD (Internal Medicine) | নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata', 'c-madina', 'c-greensign', 'c-newlife', 'c-ekota'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ১০:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'j-med-a1', name: 'Dr. Md. Atiur Rahman Sheikh', degree: 'MBBS, BCS (Health) | মেডিকেল অফিসার, সিভিল সার্জন অফিস, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata', 'c-newlife'], schedule: 'প্রতিদিন: দুপুর ১:০০ - রাত ৮:০০ (শুক্রবার বন্ধ)', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-med-r1', name: 'Dr. Md. Robiul Islam', degree: 'এমবিবিএস, এমডি (মেডিসিন) | সহকারী অধ্যাপক, মেডিসিন বিভাগ, প্রাইম মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata', 'c-pacific'], schedule: 'প্রতি বুধবার: দুপুর ২:০০ - রাত ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'j-ped1', name: 'Dr. Tabassum Mahjabin', degree: 'MBBS, BCS (Health), FCPS (Pediatrics) | ২৫০ শয্যা জেনারেল হাসপাতাল', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-janata', 'c-madina'], schedule: 'প্রতিদিন বিকাল ৪:টা – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-card1', name: 'Dr. Md. Rezwanul Haq', degree: 'MBBS, BCS (Health), MD (Cardiology) | সহযোগী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতি শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'j-orth1', name: 'Dr. Md. Abdul Jalil', degree: 'MBBS, MS (Ortho) | হাড়-জোড়া বিশেষজ্ঞ', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },

  // --- Pacific Labzone ---
  { id: 'pacific-hafiz', name: 'Dr. Md. Hafizul Islam', degree: 'MBBS (RU), BCS (Health), FCPS (Gastroenterology), FCPS (Medicine), CCD (BIRDEM) | রেজিস্ট্রার, মেডিসিন বিভাগ, রংপুর মেডিকেল কলেজ হাসপাতাল', specialty: 'Gastroenterology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি বৃহস্পতিবার: বিকাল ৩:০০ - রাত ৯:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'pacific-ali', name: 'Dr. Md. Ali', degree: 'MBBS, BCS (Health), MD (Cardiology) | সহযোগী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি সোমবার: বিকাল ৪:০০ - রাত ৯:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'pacific-shahjada', name: 'Dr. Md. Shahjada Ali', degree: 'MBBS, BCS (Health), MS (Surgery) | সহকারী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-pacific', 'c-ekota'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'pacific-alamin', name: 'Dr. Md. Al-Amin Hossain', degree: 'MBBS, BCS (Health), FCPS (Medicine) | মেডিকেল অফিসার, ২৫০ শয্যা হাসপাতাল', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'pacific-sabuj', name: 'Dr. Md. Shahinur Rahman Sabuj', degree: 'MBBS, BCS (Health), MD (Neuromedicine) | রংপুর মেডিকেল কলেজ', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'মঙ্গলবার: বিকাল ৪:০০ - রাত ৯:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'pacific-sarwar', name: 'Dr. Md. Golam Sarwar', degree: 'MBBS, BCS (Health), MS (Urology) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'pacific-robiul', name: 'Dr. Md. Robiul Islam', degree: 'এমবিবিএস, এমডি (মেডিসিন) | সহকারী অধ্যাপক, মেডিসিন বিভাগ, প্রাইম মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি বুধবার: দুপুর ২:০০ - রাত ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'pacific-gyn1', name: 'Dr. Umme Kulsum', degree: 'MBBS, BCS (Health), MS (Gynae) | গাইনী বিশেষজ্ঞ', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৭:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'pacific-ped1', name: 'Dr. Md. Atiqul Islam', degree: 'MBBS, DCH (Child) | শিশু বিশেষজ্ঞ', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন দুপুর ১:০০ - বিকাল ৫:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Madina Diagnostic ---
  { id: 'mad-hema1', name: 'Dr. Md. Abdul Kader Jilani', degree: 'MBBS, BCS (Health), FCPS (Hematology) | সহযোগী অধ্যাপক ও বিভাগীয় প্রধান, রংপুর মেডিকেল কলেজ', specialty: 'Hematology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'শুক্রবার সকাল ৯:টা – বিকাল ৩:টা', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'mad-neuro1', name: 'Dr. Md. Kaikobad Hossain', degree: 'MBBS, BCS (Health), MCPS (Medicine), FCPS (Medicine), MD (Neurology), CCD (BIRDEM) | সহকারী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'সোম, মঙ্গল, বুধ বিকাল ৩:টা – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'mad-sakib', name: 'Dr. Mostafizur Rahman (Sakib)', degree: 'MBBS, BCS (Health), MD (Nephrology - Registrar) | জাতীয় কিডনি ইনস্টিটিউট, ঢাকা', specialty: 'Nephrology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'শুক্রবার বিকাল ৪:টা – রাত ১০:টা, বুধবার সকাল ৯:টা – রাত ৮:টা', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'mad-card1', name: 'Dr. Arifuzzaman Tuhin', degree: 'MBBS, BCS (Health), MD (Cardiology) | স্যার সলিমুল্লাহ মেডিকেল কলেজ', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'শুক্রবার সকাল ৯:টা – দুপুর ২:টা', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'mad-skin1', name: 'Dr. Md. Abdul Kuddus', degree: 'MBBS, BCS (Health), CCD (Diabetology), MCPS (Dermatology & VD) | সহকারী অধ্যাপক, দিনাজপুর মেডিকেল কলেজ', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'রবিবার বিকাল ৩:টা – রাত ৮:টা', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'mad-ent1', name: 'Dr. Dhiman Pramanik', degree: 'MBBS (DMC), BCS (Health), FCPS (ENT) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'ENT', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'মঙ্গলবার বিকাল ৩:৩০ – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'mad-med1', name: 'Dr. Md. Masud Parvez', degree: 'MBBS (SSMC), BCS (Health), MD (Medicine) | নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-madina', 'c-janata'], schedule: 'শনি–বৃহস্পতিবার বিকাল ৪:টা – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'mad-orth1', name: 'Dr. Md. Asaduzzaman (Sumon)', degree: 'MBBS (DU), BCS (Health), D-Ortho (BSMMU) | রংপুর মেডিকেল কলেজ', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'সোমবার বিকাল ৩:টা – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'mad-monir', name: 'Dr. Md. Moniruzzaman (Moni)', degree: 'MBBS, BCS (Health), CCD (BIRDEM), MS (Gynae & Obs) | ২৫০ শয্যা জেনারেল হাসপাতাল', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'প্রতিদিন', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'mad-sumi', name: 'Dr. Israt Aziz (Sumi)', degree: 'MBBS, MS (Gynae & Obs) | ইনসাফ বারাকাহ মেডিকেল কলেজ, ঢাকা', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'শুক্রবার সকাল ৯:টা – রাত ৮:টা', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'mad-ped1', name: 'Dr. Tabassum Mahjabin', degree: 'MBBS, BCS (Health), FCPS (Pediatrics) | ২৫০ শয্যা জেনারেল হাসপাতাল', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'প্রতিদিন বিকাল ৪:টা – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Green Sign Hospital ---
  { id: 'gs-gyn1', name: 'Dr. Obayda Nasrin Mukta', degree: 'MBBS, BCS (Health), FCPS (Gynae & Obs) | সহকারী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শনি-বৃহস্পতি: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-ped1', name: 'Dr. Rumana (Rumki)', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (শিশু) শেষ পর্ব | কনসালটেন্ট (শিশু), ২৫০ শয্যা বিশিষ্ট জেনারেল হাসপাতাল', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শনি-বৃহস্পতি: বিকাল ৩:০০ - রাত ১০:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'gs-orth1', name: 'Dr. Md. Hamidul Haque Khandoker', degree: 'BCS (Health), PGT (Ortho), D-Ortho (Course) | নীলফামারী সদর হাসপাতাল', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ২:০০ - রাত ৪:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'gs-neuro1', name: 'Dr. Abdur Rahim', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এমসিপিএস, এফসিপিএস (মেডিসিন), এমডি (নিউরোলজি) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শনি-বৃহস্পতি: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'gs-card1', name: 'Dr. Md. Ashequr Rahman', degree: 'এমবিবিএস (ঢাকা), বিসিএস (স্বাস্থ্য), এফসিপিএস (মেডিসিন), ডি-কার্ড (কার্ডিওলজি) | কনসালটেন্ট, রংপুর মেডিকেল কলেজ', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি সোমবার: বিকাল ৪:০০ - রাত ৮:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-med1', name: 'Dr. Md. Masud Parvez', degree: 'MBBS (SSMC), BCS (Health), MD (Internal Medicine) | নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ১০:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-gyn2', name: 'Dr. Nishat Tabassum', degree: 'MBBS (BUP), PGT, CMU (Ultra), EOC (Gynae) | নীলফামারী সদর', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: সকাল ১০:০০ - দুপুর ২:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'gs-ent1', name: 'Dr. Mohammad Rashedul Islam (Rashed)', degree: 'MBBS, DLO (ENT)', specialty: 'ENT', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: সকাল ১০:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'gs-sur1', name: 'Dr. Md. Sohrab Hossain', degree: 'MBBS, FCPS (সার্জারী) জেনারেল ও ল্যাপারোস্কপিক সার্জন | সহকারী অধ্যাপক নীলফামারী মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-greensign', 'c-janata'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০ (শুক্রবার বন্ধ)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'gs-cancer1', name: 'Dr. Khandaker Mohammad Arif Hasnat', degree: 'MBBS, Cancer Specialist', specialty: 'Oncology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'সোমবার: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 1000 },
  { id: 'gs-skin1', name: 'Dr. Fahim Kiswar', degree: 'MBBS, DDV (Skin)', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শুক্রবার: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-uro1', name: 'Dr. Nuruzzaman Mia', degree: 'MBBS, MS (Urology)', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি মঙ্গলবার: দুপুর ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },

  // --- New Evercare Specialized Hospital & Diagnostic Center ---
  { id: 'ev-lucky', name: 'Dr. Mst. Sultana Razia (Lucky)', degree: 'MBBS, BCS (Health), DGO (Gynae & Obs), BMU (Former PG Hospital, Dhaka) | ২৫০ শয্যা বিশিষ্ট জেনারেল হাসপাতাল, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'প্রতিদিন: দুপুর ৩:০০ - রাত ১০:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ev-asad', name: 'Dr. Md. Asad Alam', degree: 'MBBS, BCS (Health), CCD (BIRDEM), D-CARD (Cardiology), BMU | দিনাজপুর মেডিকেল কলেজ হাসপাতাল', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'নিয়মিত চেম্বার', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ev-nripen', name: 'Dr. Nripendra Nath Roy', degree: 'MBBS (RU), MS Course (ENT), CCD (BIRDEM) | Resident Doctor, ENT Department, SSMCH, Dhaka', specialty: 'ENT', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'প্রতি শুক্রবার: বিকাল ৪:০০ - রাত ১০:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ev-iqbal', name: 'Dr. Md. Allama Iqbal (Bappi)', degree: 'MBBS, BCS (Health), MS (Urology), FCPS Final Part (Surgery) | ঢাকা মেডিকেল কলেজ হাসপাতাল, ঢাকা', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'প্রতি শনিবার: বিকাল ৩:০০ - রাত ৮:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ev-riyasad', name: 'Dr. Md. Riyasad Mahbub', degree: 'MBBS, BCS (Health), CCD (BIRDEM), PGT (Medicine), DTCD (Chest Diseases) | দিনাজপুর মেডিকেল কলেজ হাসপাতাল, দিনাজপুর', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'বৃহস্পতি: বিকাল ৪:০০ - রাত ৯:০০, শুক্রবার: সকাল ১০:০০ - বিকাল ৫:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ev-utsho', name: 'Dr. Utsho Chandra Roy', degree: 'MBBS (DMC), BCS (Health), FCPS (Internal Medicine) Part-2, MRCP-1 (London), USMLE-1 (America) | মেডিকেল অফিসার, জেনারেল হাসপাতাল, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ev-atikur', name: 'Dr. Md. Atikur Rahman', degree: 'MBBS, BCS (Health), MD (Dermatology & Venereology), BMU | কনসালটেন্ট, রংপুর মেডিকেল কলেজ হাসপাতাল, রংপুর', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'প্রতি শনিবার: বিকাল ৩:০০ - রাত ৯:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },

  // --- New Life Care Diagnostic & Consultation Center ---
  { id: 'nl-med1', name: 'Dr. Md. Masud Parvez', degree: 'MBBS (SSMC), BCS (Health), MD (Internal Medicine) | রংপুর ও নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৮:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'nl-uro1', name: 'Prof. Dr. Mohammad Mobarak Hossain', degree: 'MBBS, MS (Urology), FCPS (Surgery) | প্রাক্তন অধ্যাপক, ঢাকা মেডিকেল কলেজ হাসপাতাল', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 5.0, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 1000 },
  { id: 'nl-gyn1', name: 'Dr. Farzana Akter', degree: 'MBBS, BCS (Health), CMU, DMU (Ultrasonology) | মেডিকেল অফিসার, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'nl-med2', name: 'Dr. Md. Imran Kabir', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM), CMU | উপজেলা স্বাস্থ্য ও পরিবার পরিকল্পনা কর্মকর্তা', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ১০:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'nl-card1', name: 'Dr. Mehfuz Ali', degree: 'MBBS, BCS (Health), FCPS (Medicine), D-CARD (Cardiology) | নীলফামারী সদর হাসপাতাল, নীলফামারী', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'শনি-বৃহস্পতি: দুপুর ২:০০ - রাত ৮:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'nl-skin1', name: 'Dr. Farhanul Hasan Sifat', degree: 'MBBS, PGT (Medicine), D & C (Skin & VD), CCD (BIRDEM) | রংপুর মেডিকেল কলেজ', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-newlife', 'c-janata'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ১০:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'nl-atiar', name: 'Dr. Md. Atiur Rahman Sheikh', degree: 'MBBS, BCS (Health) | মেডিকেল অফিসার, সিভিল সার্জন অফিস, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-newlife', 'c-janata'], schedule: 'প্রতিদিন: দুপুর ১:০০ - রাত ৮:০০ (শুক্রবার বন্ধ)', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Ekota Clinic & Diagnostic Center ---
  { id: 'ek-med1', name: 'Dr. Dip Jyoti Chakraborty', degree: 'MBBS (DMC), BCS (Health), FCPS (Medicine), MD (Chest Disease) | ইন্টারভেনশনাল পালমোনলজিস্ট', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি বুধবার: দুপুর ২:০০ - ৫:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ek-card1', name: 'Dr. Md. Hasanul Islam', degree: 'MBBS, MD (Cardiology) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ হাসপাতাল', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি শুক্রবার: সকাল ৯:০০ - বিকাল ৫:০০', availableToday: false, rating: 5.0, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ek-pallab1', name: 'Dr. Pallab Kumar Das', degree: 'MBBS (SULT), M.Phil | সহযোগী অধ্যাপক, এম আব্দুর রহিম মেডিকেল কলেজ, দিনাজপুর', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি শুক্রবার: সকাল ১০:০০ - দুপুর ২:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'ek-gyn1', name: 'Dr. Abu Hena Mostafa Kamal', degree: 'MBBS, BCS (Health), FCPS (Part-2), CMU | মেডিকেল অফিসার, পার্বতীপুর', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি বৃহস্পতিবার: বিকাল ৪:০০ - রাত ৯:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ek-med2', name: 'Dr. Md. Mahbub-ul-Alam', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM) | মেডিকেল অফিসার, ২৫০ শয্যা হাসপাতাল, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-med3', name: 'Dr. S.M. Jawadul Haque', degree: 'MBBS, VTCD (Chest), PGT (Medicine) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: দুপুর ১:০০ - রাত ৮:০০ (শুক্রবন্ধ)', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ek-kid1', name: 'Dr. Nihar Ranjan Chowdhury', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM) | মেডিকেল অফিসার, ২৫০ শয্যা হাসপাতাল, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: দুপুর ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-gyn2', name: 'Dr. Maksura Khanam Matul Chowdhury', degree: 'MBBS (RU), CMU-Ultra (Dhaka) | প্রাক্তন আবাসিক মেডিকেল অফিসার', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'শনি-বৃহস্পতি: সকাল ১০:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-orth1', name: 'Dr. H.M. Sadi (Sunny)', degree: 'MBBS, BCS (Health), MS (Ortho Course), NITOR (Pangu Hospital), FCPS (FP), CMU, CCD | ট্রমা এন্ড অর্থো সার্জন (BMDC: ৭৭৬৬০)', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ek-med4', name: 'Dr. Md. Masud Parvez', degree: 'MBBS (SSMC), BCS (Health), MD (Internal Medicine) | নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ১০:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ek-gyn3', name: 'Dr. Farzana Akter', degree: 'MBBS, BCS (Health), CMU, DMU | মেডিকেল অফিসার, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-sur1', name: 'Dr. M.A. Sujon', degree: 'MBBS (Raj), BCS (Health), CMU, PGT (Surgery) | মেডিকেল অফিসার, নীলফামারী মেডিকেল কলেজ', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
];

export const CLINICS: Clinic[] = [
  { id: 'c-ar', name: 'এ.আর জেনারেল হসপিটাল', district: 'Nilphamari', address: 'সদর হাসপাতাল সড়ক (আধুনিক সদর হাসপাতালের বিপরীতে), নীলফামারী।', doctors: ['dr-ar-monir', 'dr-ar-moinul', 'dr-ar-ashequr', 'dr-ar-samiur', 'dr-ar-rupayan', 'dr-ar-deb', 'dr-ar-ruhul', 'dr-ar-tawhid', 'dr-ar-shamsur', 'dr-ar-matin', 'dr-ar-awal'], image: 'https://images.unsplash.com/photo-1587350859728-117699f8aee1?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ebadot', name: 'ইবাদত হাসপাতাল', district: 'Nilphamari', address: 'পুরাতন স্টেশন সড়ক, নীলফামারী', doctors: ['dr-eb-koushik', 'dr-eb-tuli', 'dr-eb-mezba', 'dr-eb-munira', 'dr-eb-rezaul', 'dr-eb-firoz', 'dr-eb-sakura'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-moun', name: 'মৌন জেনারেল হাসপাতাল অ্যান্ড ডায়াগনস্টিক সেন্টার', district: 'Nilphamari', address: 'নীলফামারী সদর', doctors: ['dr-moun-shankar', 'dr-moun-lopa'], image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-pacific', name: 'প্যাসিফিক ল্যাবজোন', district: 'Nilphamari', address: 'পুরাতন বাসস্ট্যান্ড, স্টাফ কোয়ার্টার সংলগ্ন, নীলফামারী।', doctors: ['dr-pac-hafizul', 'dr-pac-ali', 'dr-pac-shahjada', 'dr-pac-alamin', 'dr-pac-sabuj', 'dr-pac-sarwar', 'dr-pac-robiul', 'dr-pac-altaf', 'dr-pac-kayes', 'dr-pac-ayesha', 'dr-pac-selimuzzaman'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-janata', name: 'জনতা ক্লিনিক এন্ড ডায়াগনস্টিক সেন্টার', district: 'Nilphamari', address: 'শান্তিনগর মোড় (ব্রিজ সংলগ্ন), হাসপাতাল সড়ক, নীলফামারী।', doctors: ['dr-j-parul', 'dr-j-farzana', 'dr-j-afroza', 'dr-j-sohrab', 'dr-j-abdullah', 'dr-j-nihar', 'dr-j-tawhida', 'dr-j-atiur', 'dr-j-masud', 'dr-j-rituparna', 'dr-j-komlakanto'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ekota', name: 'একতা ক্লিনিক এন্ড ডায়াগনস্টিক সেন্টার', district: 'Nilphamari', address: 'জেনারেল হাসপাতাল সড়ক, শান্তিনগর মোড় (কানছিড়ার মোড়), নীলফামারী', doctors: ['dr-ek-dip', 'dr-ek-hasanul', 'dr-ek-pallab', 'dr-ek-abuna', 'dr-ek-mahbub', 'dr-ek-forhad', 'dr-ek-nihar', 'dr-ek-maksura', 'dr-ek-sadi', 'dr-ek-masud', 'dr-ek-farzana', 'dr-ek-sujon'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-madina', name: 'Madina Diagnostic Clinic & Consultation', district: 'Nilphamari', address: 'জেনারেল হাসপাতাল রোড, হাসপাতাল মোড়, নীলফামারী', doctors: ['dr-mad-jilani', 'dr-mad-kaikobad', 'dr-mad-sakib', 'dr-mad-tuhin', 'dr-mad-kuddus', 'dr-mad-dhiman', 'dr-mad-masud', 'dr-mad-sumon', 'dr-mad-monir', 'dr-mad-sumi', 'dr-mad-tabassum'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-greensign', name: 'Green Sign Hospital & Diagnostic Lab', district: 'Nilphamari', address: 'নীলফামারী সদর', doctors: ['dr-gs-mukta', 'dr-gs-moazzem', 'dr-gs-rahim', 'dr-gs-asad', 'dr-gs-asad_alam', 'dr-gs-mehfuz', 'dr-gs-rumana', 'dr-gs-rashedul', 'dr-gs-sohrab', 'dr-gs-hasnat', 'dr-gs-kiswar', 'dr-gs-imran', 'dr-gs-nuru-zaman'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-newlife', name: 'New Life Care Diagnostic & Consultation Center', district: 'Nilphamari', address: 'চৌরঙ্গী মোড় (হাসপাতাল সড়ক), পোস্ট অফিস সংলগ্ন, নীলফামারী', doctors: ['dr-nl-masud', 'dr-nl-mobarek', 'dr-nl-farzana', 'dr-nl-imran', 'dr-nl-mehedi', 'dr-nl-sifat'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
];

export const EMERGENCY_SERVICES = [
  { id: 'e1', name: 'ECG (ইসিজি)', price: 600, icon: '💓', description: 'বাসায় গিয়ে ইসিজি করা হয়' },
  { id: 'e2', name: 'Blood Collection', price: 200, icon: '🩸', description: 'ল্যাব টেস্টের জন্য রক্ত সংগ্রহ' },
  { id: 'e3', name: 'Nurse Care', price: 1500, icon: '👩‍⚕️', description: 'দক্ষ নার্সিং সেবা (১২ ঘণ্টা)' },
  { id: 'e4', name: 'BP Check', price: 100, icon: '🩺', description: 'ব্লাড প্রেসার ও সুগার চেক' },
];

export const LAB_TESTS: LabTest[] = [];

export const MEDICINES: Medicine[] = [
  { id: 'm1', name: 'Napa Extend', price: 20, discount: 5, image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=200', description: 'Pain relief' },
  { id: 'm2', name: 'Seclo 20', price: 150, discount: 10, image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=200', description: 'Acidity' },
  { id: 'm3', name: 'Fexo 120', price: 90, discount: 0, image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=200', description: 'Allergy' },
];
