
import { Doctor, Clinic, Medicine, LabTest } from './types';

export const DISTRICTS = ['Dhaka', 'Chattogram', 'Sylhet', 'Rajshahi', 'Khulna', 'Barishal', 'Rangpur', 'Mymensingh', 'Nilphamari'];

export const SPECIALTIES = [
  { id: 'medicine', name: 'Medicine', icon: '💊', bnName: 'মেডিসিন' },
  { id: 'cardiology', name: 'Cardiology', icon: '🫀', bnName: 'হৃদরোগ' },
  { id: 'neuromedicine', name: 'Neuromedicine', icon: '🧠', bnName: 'নিউরোলজি' },
  { id: 'gynecology', name: 'Gynecology', icon: '🤰', bnName: 'গাইনী' },
  { id: 'orthopedics', name: 'Orthopedics', icon: '🦴', bnName: 'হাড়-জোড়া' },
  { id: 'pediatrics', name: 'Pediatrics', icon: '👶', bnName: 'শিশু' },
  { id: 'surgery', name: 'Surgery', icon: '🔪', bnName: 'সার্জারি' },
  { id: 'urology', name: 'Urology', icon: '💧', bnName: 'ইউরোলজি' },
  { id: 'endocrinology', name: 'Endocrinology', icon: '🩸', bnName: 'ডায়াবেটিস' },
  { id: 'ent', name: 'ENT', icon: '👂', bnName: 'নাক-কান-গলা' },
  { id: 'dermatology', name: 'Dermatology', icon: '✨', bnName: 'চর্ম-যৌন' },
  { id: 'ophthalmology', name: 'Ophthalmology', icon: '👁️', bnName: 'চক্ষু' },
  { id: 'psychiatry', name: 'Psychiatry', icon: '🧘', bnName: 'মানসিক' },
  { id: 'dentistry', name: 'Dentistry', icon: '🦷', bnName: 'দন্ত' },
  { id: 'gastroenterology', name: 'Gastroenterology', icon: '🧪', bnName: 'পরিপাকতন্ত্র' },
  { id: 'kidney', name: 'Nephrology', icon: '💧', bnName: 'কিডনি' },
  { id: 'cancer', name: 'Oncology', icon: '🧬', bnName: 'ক্যান্সার' },
  { id: 'hematology', name: 'Hematology', icon: '🩸', bnName: 'রক্তরোগ' },
];

export const DOCTORS: Doctor[] = [
  // --- AR General Hospital ---
  { id: 'ar-gyn1', name: 'Dr. Md. Moniruzzaman Moni', degree: 'MBBS, BCS (Health), CCD (BIRDEM), MS (Gynae & Obs) | কনসালটেন্ট, ২৫০ শয্যা জেনারেল হাসপাতাল, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ar-uro1', name: 'Dr. Md. Moinul Haque Chowdhury', degree: 'MBBS, BCS (Health), FCPS (Urology) | সহকারী অধ্যাপক, NICVDU, ঢাকা', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: দুপুর ২:০০ - রাত ৮:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ar-med1', name: 'Dr. Md. Ashequr Rahman', degree: 'MBBS (Dhaka), BCS (Health), FCPS (Medicine), D-CARD (Cardiology), MACP (USA) | কনসালটেন্ট, রংপুর মেডিকেল কলেজ', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ar-card1', name: 'Dr. Md. Samiur Rahman Shah', degree: 'MBBS, BCS (Health), CCD (BIRDEM), MD (Cardiology), FCPS (Medicine), MACP (USA), FACC (USA) | ইন্টারভেনশনাল কার্ডিওলজিস্ট, জাতীয় হৃদরোগ ইনস্টিটিউট', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: সকাল ১০:০০ - रात ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ar-orth1', name: 'Dr. Roopayon Das', degree: 'MBBS, BCS (Health), D-Ortho | কনসালটেন্ট, উপজেলা স্বাস্থ্য কমপ্লেক্স', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: দুপুর ২:০০ - রাত ৮:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ar-psy1', name: 'Dr. Deb Dulal Roy', degree: 'MBBS, BCS (Health), CCD (BIRDEM), MD (Psychiatry) | BMU ও রংপুর মেডিকেল কলেজ', specialty: 'Psychiatry', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'বৃহস্পতিবার: বিকাল ৪:০০ - রাত ৯:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 1000 },
  { id: 'ar-neuro1', name: 'Dr. Md. Ruhul Amin', degree: 'MBBS, Neurology Specialist | সহযোগী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'মঙ্গলবার: বিকাল ৪:০০ - রাত ৯:০০, শুক্রবার: সকাল ১০:০০ - ১১:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ar-endo1', name: 'Dr. S.M. Tawhid Hasan', degree: 'MBBS, BCS (Health), DM (Endocrinology), FCPS (Endocrinology), Mayo Clinic Training | BSMMU', specialty: 'Endocrinology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: সকাল ৯:০০ - দুপুর ২:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'ar-med2', name: 'Dr. Md. Shamsur Rahman', degree: 'MBBS, BCS (Health), Medicine Specialist | সহকারী অধ্যাপক', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'রবি, সোম, বুধ: বিকাল ৪:০০ - রাত ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ar-med3', name: 'Dr. Md. Abdul Matin', degree: 'MBBS, BCS (Health), Medicine Specialist | সহকারী অধ্যাপক', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শনি-বৃহস্পতি: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Roots Eye Operation & Consultation Center ---
  { id: 'roots-eye1', name: 'Dr. Md. Mizanur Rahman', degree: 'MBBS, MS (Ophthalmology), BCS (Health) | সহযোগী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Ophthalmology', districts: ['Nilphamari'], clinics: ['c-roots'], schedule: 'সময়: (যোগাযোগ করুন)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'roots-eye2', name: 'Dr. Md. Kamrul Hasan', degree: 'MBBS (Rajshahi), BCS (Health), MS (Ophthalmology) | কনসালটেন্ট, ২৫০ শয্যা হাসপাতাল', specialty: 'Ophthalmology', districts: ['Nilphamari'], clinics: ['c-roots'], schedule: 'সময়: (যোগাযোগ করুন)', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },

  // --- Ebadot Hospital (New) ---
  { id: 'eb-sohel', name: 'Dr. Md. Sohelur Rahman Sohel', degree: 'MBBS (Rangpur Medical), D-Ortho Surgery, PRP Therapy & Ilizarov Fellowship, AO Trauma & APOA Member | হাড় ভাঙা, বাত ও ব্যথা বিশেষজ্ঞ', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতিদিন ২:০০ PM – ৯:০০ PM (শুক্রবার বন্ধ)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'eb-koushik', name: 'Dr. Koushik Roy', degree: 'MBBS | নবজাতক, শিশু ও কিশোর রোগ বিশেষজ্ঞ', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'যোগাযোগ করুন', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'eb-tuli', name: 'Dr. Sultana Nasera Tuli', degree: 'MBBS, BCS (Health), FCPS (Gynae & Obs) | Registrar, ২৫০ শয্যা জেনারেল হাসপাতাল, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শনি – বৃহস্পতি: ৩:৩০ PM – ১০:০০ PM', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'eb-riyasad', name: 'Dr. Md. Riyasad Mahabub', degree: 'MBBS, BCS (Health), CCD (BIRDEM), PGT (Medicine), DTCD (Chest Diseases) | বক্ষব্যাধি, অ্যাজমা ও ডায়াবেটিস বিশেষজ্ঞ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শনি ও সোম: ৩:৩০ PM – ৯:০০ PM', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'eb-rouf', name: 'Dr. Md. Mostafa Kamal Rouf', degree: 'MBBS, BCS (Health), FCPS (Medicine), Post Graduate Training (Neurology & Cardiology) | সহযোগী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'মঙ্গল: ৩:০০ PM – ১০:০০ PM, বুধ: ৩:০০ PM – ৬:০০ PM', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'eb-mahbub', name: 'Dr. Md. Mahabub-ul-Alam', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM) | প্রভাষক, নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শনি – বুধ: ৩:০০ PM – ৯:০০ PM', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'eb-mezbah', name: 'Dr. Mezbahul Mukarrabin Mezba', degree: 'MBBS, BCS (Health), MS (Urology), Advanced Training (Australia) | ইউরোলজি বিশেষজ্ঞ', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'মঙ্গলবার: ৩:০০ PM – ৮:০০ PM', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'eb-rony', name: 'Dr. Md. Zillur Hassan Rony', degree: 'MBBS, BCS (Health), MS (Orthopedics) – NITOR, FACS (USA), AO Training | অর্থোপেডিক বিশেষজ্ঞ ও সার্জন', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শুক্রবার: ১০:০০ AM – ৭:০০ PM', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'eb-munira', name: 'Dr. Munira Ferdous', degree: 'MBBS, DDV, CCD (BIRDEM), Fellowship in Dermatosurgery & Aesthetic Dermatology | চর্ম, যৌন ও সৌন্দর্য বিশেষজ্ঞ', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শুক্রবার: ১০:০০ AM – ৪:০০ PM', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'eb-firoz', name: 'Dr. Md. Firoz Hossain', degree: 'MBBS, DLO (BSMMU) | সহযোগী অধ্যাপক, রংপুর কমিউনিটি মেডিকেল কলেজ', specialty: 'ENT', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শুক্রবার: ১০:০০ AM – ৫:০০ PM', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'eb-saiful', name: 'Dr. Md. Saiful Islam', degree: 'MBBS, BCS (Health), MD (Cardiology), FCPS (Medicine), PGT (Neuro Medicine) | হৃদরোগ ও মেডিসিন বিশেষজ্ঞ', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'বৃহস্পতিবার: ৩:০০ PM – ৯:০০ PM', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'eb-narayan', name: 'Dr. Narayan Chandra Roy Joy', degree: 'MBBS (Dhaka), BCS (Health), FCPS (Neurosurgery) | সহকারী রেজিস্ট্রার, ঢাকা মেডিকেল কলেজ', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শুক্রবার: ৩:০০ PM – ১০:০০ PM', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'eb-sobur', name: 'Dr. Md. Abdus Sobur Khan', degree: 'MBBS, BCS (Health), CCD (Diabetes), BIRDEM, MD (Nephrology), BMU, Dhaka, MACP (America) | সহকারী অধ্যাপক, নেফ্রোলজি (কিডনী) বিভাগ, রংপুর মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Nephrology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'শুক্রবার: ১০:০০ AM – ০৬:০০ PM', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },

  // --- Moun General Hospital ---
  { id: 'moun-gyn1', name: 'Dr. Nishat Tabassum', degree: 'MBBS (BUP), PGT, CMU (Ultra), EOC (Gynae) | RMO', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'প্রতিদিন', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'moun-gyn2', name: 'Dr. Mahfuza Akter (Lopa)', degree: 'MBBS, BCS (Health), MS (Gynae & Obs) | কনসালটেন্ট, রংপুর মেডিকেল', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'moun-sur1', name: 'Dr. Mohammad Wajibullah', degree: 'MBBS, BCS, MRCS, MS (Colorectal Surgery) | সহকারী অধ্যাপক', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'শুক্রবার: সকাল ১১:০০ - বিকাল ৪:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'moun-card1', name: 'Dr. Shankar Kumar Saha', degree: 'MBBS, D-CARD | সিনিয়র কনসালটেন্ট', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'সোমবার: ৩:০০ - ৮:০০, শুক্রবার: ১১:০০ - ৪:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  // --- Janata Clinic & Diagnostic Center ---
  { id: 'j-gyn1', name: 'Dr. Parul Rani Roy', degree: 'MBBS, DGO (Dhaka), FCPS (LP), Gynae & Obs | Ex-Consultant Labaid', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-sur1', name: 'Dr. M.A. Sujon', degree: 'MBBS (Raj), BCS (Health), CMU, PGT (Surgery) | মেডিকেল অফিসার, নীলফামারী মেডিকেল কলেজ', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'j-gyn3', name: 'Dr. Farzana Akter', degree: 'MBBS, BCS (Health), CMU, DMU | মেডিকেল অফিসার, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-sur2', name: 'Dr. Md. Sohrab Hossain', degree: 'MBBS, FCPS (সার্জারী) জেনারেল ও ল্যাপারোস্কপিক সার্জন | সহকারী অধ্যাপক নীলফামারী মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০ (শুক্রবার বন্ধ)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'j-kid1', name: 'Dr. Nihar Ranjan Chowdhury', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM) | মেডিকেল অফিসার, ২৫০ শয্যা হাসপাতাল, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: দুপুর ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-med-t1', name: 'Dr. Md. Masud Parvez', degree: 'MBBS (SSMC), BCS (Health), MD (Internal Medicine) | নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ১০:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'j-med-a1', name: 'Dr. Md. Atiur Rahman Sheikh', degree: 'MBBS, BCS (Health) | মেডিকেল অফিসার, সিভিল সার্জন অফিস, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: দুপুর ১:০০ - রাত ৮:০০ (শুক্রবার বন্ধ)', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-med-r1', name: 'Dr. Md. Robiul Islam', degree: 'এমবিবিএস, এমডি (মেডিসিন) | সহকারী অধ্যাপক, মেডিসিন বিভাগ, প্রাইম মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতি বুধবার: দুপুর ২:০০ - রাত ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'j-ped1', name: 'Dr. Tabassum Mahjabin', degree: 'MBBS, BCS (Health), FCPS (Pediatrics) | ২৫০ শয্যা জেনারেল হাসপাতাল', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন বিকাল ৪:টা – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Pacific Labzone ---
  { id: 'pacific-hafiz', name: 'Dr. Md. Hafizul Islam', degree: 'MBBS (RU), BCS (Health), FCPS (Gastroenterology), FCPS (Medicine), CCD (BIRDEM) | রেজিস্ট্রার, মেডিসিন বিভাগ, রংপুর মেডিকেল কলেজ হাসপাতাল', specialty: 'Gastroenterology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি বৃহস্পতিবার: বিকাল ৩:০০ - রাত ৯:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'pacific-ali', name: 'Dr. Md. Ali', degree: 'MBBS, BCS (Health), MD (Cardiology) | সহযোগী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি সোমবার: বিকাল ৪:০০ - রাত ৯:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'pacific-shahjada', name: 'Dr. Md. Shahjada Ali', degree: 'MBBS, BCS (Health), MS (Surgery) | সহকারী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'pacific-alamin', name: 'Dr. Md. Al-Amin Hossain', degree: 'MBBS, BCS (Health), FCPS (Medicine) | মেডিকেল অফিসার, ২৫০ শয্যা হাসপাতাল', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'pacific-sabuj', name: 'Dr. Md. Shahinur Rahman Sabuj', degree: 'MBBS, BCS (Health), MD (Neuromedicine) | রংপুর মেডিকেল কলেজ', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'মঙ্গলবার: বিকাল ৪:০০ - রাত ৯:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'pacific-sarwar', name: 'Dr. Md. Golam Sarwar', degree: 'MBBS, BCS (Health), MS (Urology) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'pacific-robiul', name: 'Dr. Md. Robiul Islam', degree: 'এমবিবিএস, এমডি (মেডিসিন) | সহকারী অধ্যাপক, মেডিসিন বিভাগ, প্রাইম মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি বুধবার: দুপুর ২:০০ - রাত ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },

  // --- Madina Diagnostic ---
  { id: 'mad-hema1', name: 'Dr. Md. Abdul Kader Jilani', degree: 'MBBS, BCS (Health), FCPS (Hematology) | সহযোগী অধ্যাপক ও বিভাগীয় প্রধান, রংপুর মেডিকেল কলেজ', specialty: 'Hematology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'শুক্রবার সকাল ৯:টা – বিকাল ৩:টা', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'mad-neuro1', name: 'Dr. Md. Kaikobad Hossain', degree: 'MBBS, BCS (Health), MCPS (Medicine), FCPS (Medicine), MD (Neurology), CCD (BIRDEM) | সহকারী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'সোম, মঙ্গল, বুধ বিকাল ৩:টা – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'mad-sakib', name: 'Dr. Mostafizur Rahman (Sakib)', degree: 'MBBS, BCS (Health), MD (Nephrology - Registrar) | জাতীয় কিডনি ইনস্টিটিউট, ঢাকা', specialty: 'Nephrology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'শুক্রবার বিকাল ৪:টা – রাত ১০:টা, বুধবার সকাল ৯:টা – রাত ৮:টা', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'mad-card1', name: 'Dr. Arifuzzaman Tuhin', degree: 'MBBS, BCS (Health), MD (Cardiology) | স্যার সলিমুল্লাহ মেডিকেল কলেজ', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'শুক্রবার সকাল ৯:টা – দুপুর ২:টা', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'mad-skin1', name: 'Dr. Md. Abdul Kuddus', degree: 'MBBS, BCS (Health), CCD (Diabetology), MCPS (Dermatology & VD) | সহকারী অধ্যাপক, দিনাজপুর মেডিকেল কলেজ', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'রবিবার বিকাল ৩:টা – রাত ৮:টা', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'mad-ent1', name: 'Dr. Dhiman Pramanik', degree: 'MBBS (DMC), BCS (Health), FCPS (ENT) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'ENT', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'মঙ্গলবার বিকাল ৩:৩০ – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'mad-med1', name: 'Dr. Md. Masud Parvez', degree: 'MBBS (SSMC), BCS (Health), MD (Medicine) | নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-madina', 'c-janata'], schedule: 'শনি–বৃহস্পতিবার বিকাল ৪:টা – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'mad-orth1', name: 'Dr. Md. Asaduzzaman (Sumon)', degree: 'MBBS (DU), BCS (Health), D-Ortho (BSMMU) | রংপুর মেডিকেল কলেজ', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'সোমবার বিকাল ৩:টা – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'mad-monir', name: 'Dr. Md. Moniruzzaman (Moni)', degree: 'MBBS, BCS (Health), CCD (BIRDEM), MS (Gynae & Obs) | ২৫০ শয্যা জেনারেল হাসপাতাল', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'প্রতিদিন', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'mad-sumi', name: 'Dr. Israt Aziz (Sumi)', degree: 'MBBS, MS (Gynae & Obs) | ইনসাফ বারাকাহ মেডিকেল কলেজ, ঢাকা', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'শুক্রবার সকাল ৯:টা – রাত ৮:টা', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'mad-ped1', name: 'Dr. Tabassum Mahjabin', degree: 'MBBS, BCS (Health), FCPS (Pediatrics) | ২৫০ শয্যা জেনারেল হাসপাতাল', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'প্রতিদিন বিকাল ৪:টা – রাত ৮:টা', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Green Sign Hospital ---
  { id: 'gs-gyn1', name: 'Dr. Obayda Nasrin Mukta', degree: 'MBBS, BCS (Health), FCPS (Gynae & Obs) | সহকারী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শনি-বৃহস্পতি: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-ped1', name: 'Dr. Rumana (Rumki)', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (শিশু) শেষ পর্ব | কনসালটেন্ট (শিশু), ২৫০ শয্যা বিশিষ্ট জেনারেল হাসপাতাল', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শনি-বৃহস্পতি: বিকাল ৩:০০ - রাত ১০:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'gs-orth1', name: 'Dr. Md. Hamidul Haque Khandoker', degree: 'BCS (Health), PGT (Ortho), D-Ortho (Course) | নীলফামারী সদর হাসপাতাল', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ২:০০ - রাত ৪:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'gs-neuro1', name: 'Dr. Abdur Rahim', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এমসিপিএস, এফসিপিএস (মেডিসিন), এমডি (নিউরোলজি) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শনি-বৃহস্পতি: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'gs-card1', name: 'Dr. Md. Ashequr Rahman', degree: 'এমবিবিএস (ঢাকা), বিসিএস (স্বাস্থ্য), এফসিপিএস (মেডিসিন), ডি-কার্ড (কার্ডিওলজি) | কনসালটেন্ট, রংপুর মেডিকেল কলেজ', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি সোমবার: বিকাল ৪:০০ - রাত ৮:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-med1', name: 'Dr. Md. Masud Parvez', degree: 'MBBS (SSMC), BCS (Health), MD (Internal Medicine) | নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ১০:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-gyn2', name: 'Dr. Nishat Tabassum', degree: 'MBBS (BUP), PGT, CMU (Ultra), EOC (Gynae) | নীলফামারী সদর', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: সকাল ১০:০০ - দুপুর ২:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'gs-ent1', name: 'Dr. Mohammad Rashedul Islam (Rashed)', degree: 'MBBS, DLO (ENT)', specialty: 'ENT', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: সকাল ১০:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'gs-sur1', name: 'Dr. Md. Sohrab Hossain', degree: 'MBBS, FCPS (সার্জারী) জেনারেল ও ল্যাপারোস্কপিক সার্জন | সহকারী অধ্যাপক নীলফামারী মেডিকেল কলেজ ও হাসপাতাল', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-greensign', 'c-janata'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০ (শুক্রবার বন্ধ)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'gs-cancer1', name: 'Dr. Khandaker Mohammad Arif Hasnat', degree: 'MBBS, Cancer Specialist', specialty: 'Oncology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'সোমবার: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 1000 },
  { id: 'gs-skin1', name: 'Dr. Fahim Kiswar', degree: 'MBBS, DDV (Skin)', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শুক্রবার: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-uro1', name: 'Dr. Nuruzzaman Mia', degree: 'MBBS, MS (Urology)', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি মঙ্গলবার: দুপুর ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },

  // --- New Evercare Specialized Hospital & Diagnostic Center ---
  { id: 'ev-lucky', name: 'Dr. Mst. Sultana Razia (Lucky)', degree: 'MBBS, BCS (Health), DGO (Gynae & Obs), BMU (Former PG Hospital, Dhaka) | ২৫০ শয্যা বিশিষ্ট জেনারেল হাসপাতাল, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'প্রতিদিন: দুপুর ৩:০০ - রাত ১০:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ev-asad', name: 'Dr. Md. Asad Alam', degree: 'MBBS, BCS (Health), CCD (BIRDEM), D-CARD (Cardiology), BMU | দিনাজপুর মেডিকেল কলেজ হাসপাতাল', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'নিয়মিত চেম্বার', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ev-nripen', name: 'Dr. Nripendra Nath Roy', degree: 'MBBS (RU), MS Course (ENT), CCD (BIRDEM) | Resident Doctor, ENT Department, SSMCH, Dhaka', specialty: 'ENT', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'প্রতি শুক্রবার: বিকাল ৪:০০ - রাত ১০:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ev-iqbal', name: 'Dr. Md. Allama Iqbal (Bappi)', degree: 'MBBS, BCS (Health), MS (Urology), FCPS Final Part (Surgery) | ঢাকা মেডিকেল কলেজ হাসপাতাল, ঢাকা', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'প্রতি শনিবার: বিকাল ৩:০০ - রাত ৮:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ev-riyasad', name: 'Dr. Md. Riyasad Mahbub', degree: 'MBBS, BCS (Health), CCD (BIRDEM), PGT (Medicine), DTCD (Chest Diseases) | দিনাজপুর মেডিকেল কলেজ হাসপাতাল, দিনাজপুর', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'বৃহস্পতি: বিকাল ৪:০০ - রাত ৯:০০, শুক্রবার: সকাল ১০:০০ - বিকাল ৫:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ev-utsho', name: 'Dr. Utsho Chandra Roy', degree: 'MBBS (DMC), BCS (Health), FCPS (Internal Medicine) Part-2, MRCP-1 (London), USMLE-1 (America) | মেডিকেল অফিসার, জেনারেল হাসপাতাল, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ev-atikur', name: 'Dr. Md. Atikur Rahman', degree: 'MBBS, BCS (Health), MD (Dermatology & Venereology), BMU | কনসালটেন্ট, রংপুর মেডিকেল কলেজ হাসপাতাল, রংপুর', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-evercare-spec'], schedule: 'প্রতি শনিবার: বিকাল ৩:০০ - রাত ৯:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },

  // --- New Life Care Diagnostic & Consultation Center ---
  { id: 'nl-med1', name: 'Dr. Md. Masud Parvez', degree: 'MBBS (SSMC), BCS (Health), MD (Internal Medicine) | রংপুর ও নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৮:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'nl-uro1', name: 'Prof. Dr. Mohammad Mobarak Hossain', degree: 'MBBS, MS (Urology), FCPS (Surgery) | প্রাক্তন অধ্যাপক, ঢাকা মেডিকেল কলেজ হাসপাতাল', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 5.0, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 1000 },
  { id: 'nl-gyn1', name: 'Dr. Farzana Akter', degree: 'MBBS, BCS (Health), CMU, DMU (Ultrasonology) | মেডিকেল অফিসার, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'nl-med2', name: 'Dr. Md. Imran Kabir', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM), CMU | উপজেলা স্বাস্থ্য ও পরিবার পরিকল্পনা কর্মকর্তা', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ১০:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'nl-card1', name: 'Dr. Mehfuz Ali', degree: 'MBBS, BCS (Health), FCPS (Medicine), D-CARD (Cardiology) | নীলফামারী সদর হাসপাতাল, নীলফামারী', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'শনি-বৃহস্পতি: দুপুর ২:০০ - রাত ৮:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'nl-skin1', name: 'Dr. Farhanul Hasan Sifat', degree: 'MBBS, PGT (Medicine), D & C (Skin & VD), CCD (BIRDEM) | রংপুর মেডিকেল কলেজ', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-newlife', 'c-janata'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ১০:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'nl-atiar', name: 'Dr. Md. Atiur Rahman Sheikh', degree: 'MBBS, BCS (Health) | মেডিকেল অফিসার, সিভিল সার্জন অফিস, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-newlife', 'c-janata'], schedule: 'প্রতিদিন: দুপুর ১:০০ - রাত ৮:০০ (শুক্রবার বন্ধ)', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Ekota Clinic & Diagnostic Center ---
  { id: 'ek-med1', name: 'Dr. Dip Jyoti Chakraborty', degree: 'MBBS (DMC), BCS (Health), FCPS (Medicine), MD (Chest Disease) | ইন্টারভেনশনাল পালমোনলজিস্ট', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি বুধবার: দুপুর ২:০০ - ৫:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ek-card1', name: 'Dr. Md. Hasanul Islam', degree: 'MBBS, MD (Cardiology) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ হাসপাতাল', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি শুক্রবার: সকাল ৯:০০ - বিকাল ৫:০০', availableToday: false, rating: 5.0, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ek-pallab1', name: 'Dr. Pallab Kumar Das', degree: 'MBBS (SULT), M.Phil | সহযোগী অধ্যাপক, এম আব্দুর রহিম মেডিকেল কলেজ, দিনাজপুর', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি শুক্রবার: সকাল ১০:০০ - দুপুর ২:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'ek-gyn1', name: 'Dr. Abu Hena Mostafa Kamal', degree: 'MBBS, BCS (Health), FCPS (Part-2), CMU | মেডিকেল অফিসার, পার্বতীপুর', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি বৃহস্পতিবার: বিকাল ৪:০০ - রাত ৯:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ek-med2', name: 'Dr. Md. Mahbub-ul-Alam', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM) | মেডিকেল অফিসার, ২৫০ শয্যা হাসপাতাল, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-med3', name: 'Dr. S.M. Jawadul Haque', degree: 'MBBS, VTCD (Chest), PGT (Medicine) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: দুপুর ১:০০ - রাত ৮:০০ (শুক্রবন্ধ)', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ek-kid1', name: 'Dr. Nihar Ranjan Chowdhury', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM) | মেডিকেল অফিসার, ২৫০ শয্যা হাসপাতাল, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: দুপুর ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-gyn2', name: 'Dr. Maksura Khanam Matul Chowdhury', degree: 'MBBS (RU), CMU-Ultra (Dhaka) | প্রাক্তন আবাসিক মেডিকেল অফিসার', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'শনি-বৃহস্পতি: সকাল ১০:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-orth1', name: 'Dr. H.M. Sadi (Sunny)', degree: 'MBBS, BCS (Health), MS (Ortho Course), NITOR (Pangu Hospital), FCPS (FP), CMU, CCD | ট্রমা এন্ড অর্থো সার্জন (BMDC: ৭৭৬৬০)', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ek-med4', name: 'Dr. Md. Masud Parvez', degree: 'MBBS (SSMC), BCS (Health), MD (Internal Medicine) | নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ১০:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ek-gyn3', name: 'Dr. Farzana Akter', degree: 'MBBS, BCS (Health), CMU, DMU | মেডিকেল অফিসার, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-sur1', name: 'Dr. M.A. Sujon', degree: 'MBBS (Raj), BCS (Health), CMU, PGT (Surgery) | মেডিকেল অফিসার, নীলফামারী মেডিকেল কলেজ', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
];

export const CLINICS: Clinic[] = [
  { id: 'c-madina', name: 'Madina Diagnostic Clinic & Consultation', district: 'Nilphamari', address: 'জেনারেল হাসপাতাল রোড, হাসপাতাল মোড়, নীলফামারী', doctors: ['mad-hema1', 'mad-neuro1', 'mad-sakib', 'mad-card1', 'mad-skin1', 'mad-ent1', 'mad-med1', 'mad-orth1', 'mad-monir', 'mad-sumi', 'mad-ped1'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-greensign', name: 'Green Sign Hospital & Diagnostic Lab', district: 'Nilphamari', address: 'নীলফামারী সদর', doctors: ['gs-gyn1', 'gs-ped1', 'gs-orth1', 'gs-neuro1', 'gs-card1', 'gs-med1', 'gs-gyn2', 'gs-ent1', 'gs-sur1', 'gs-cancer1', 'gs-skin1', 'gs-uro1'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ar', name: 'AR General Hospital', district: 'Nilphamari', address: 'সদর হাসপাতাল রোড, নীলফামারী', doctors: ['ar-gyn1', 'ar-uro1', 'ar-med1', 'ar-card1', 'ar-orth1', 'ar-psy1', 'ar-neuro1', 'ar-endo1', 'ar-med2', 'ar-med3'], image: 'https://images.unsplash.com/photo-1587350859728-117699f8aee1?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-janata', name: 'Janata Clinic & Diagnostic Center', district: 'Nilphamari', address: 'শান্তিনগর মোড় (ব্রিজ সংলগ্ন), হাসপাতাল সড়ক, নীলফামারী', doctors: ['j-gyn1', 'j-sur1', 'j-gyn3', 'gs-sur1', 'j-sur2', 'j-kid1', 'j-med-t1', 'j-med-a1', 'mad-med1', 'j-med-r1', 'j-ped1'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-roots', name: 'Roots Eye Operation & Consultation Center', district: 'Nilphamari', address: 'নীলফামারী সদর', doctors: ['roots-eye1', 'roots-eye2'], image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-moun', name: 'Moun General Hospital & Diagnostic Center', district: 'Nilphamari', address: 'নীলফামারী সদর', doctors: ['moun-gyn1', 'moun-gyn2', 'moun-sur1', 'moun-card1'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-pacific', name: 'Pacific Labzone', district: 'Nilphamari', address: 'নীলফামারী', doctors: ['pacific-hafiz', 'pacific-ali', 'pacific-shahjada', 'pacific-alamin', 'pacific-sabuj', 'pacific-sarwar', 'pacific-robiul'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ebadot', name: 'Ebadot Hospital', district: 'Nilphamari', address: 'পুরাতন স্টেশন সড়ক, নীলফামারী', doctors: ['eb-sohel', 'eb-koushik', 'eb-tuli', 'eb-riyasad', 'eb-rouf', 'eb-mahbub', 'eb-mezbah', 'eb-rony', 'eb-munira', 'eb-firoz', 'eb-saiful', 'eb-narayan', 'eb-sobur'], image: 'https://images.unsplash.com/photo-1587350859728-117699f8aee1?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-evercare-spec', name: 'New Evercare Specialized Hospital & Diagnostic Center', district: 'Nilphamari', address: 'হাসপাতাল সড়ক, শান্তিনগর মোড়, নীলফামারী', doctors: ['ev-lucky', 'ev-asad', 'ev-nripen', 'ev-iqbal', 'ev-riyasad', 'ev-utsho', 'ev-atikur'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-newlife', name: 'New Ever Care Hospital & Diagnostic Center', district: 'Nilphamari', address: 'চৌরঙ্গী মোড় (হাসপাতাল সড়ক), নীলফামারী', doctors: ['nl-med1', 'nl-uro1', 'nl-gyn1', 'nl-med2', 'nl-card1', 'nl-skin1', 'nl-atiar'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ekota', name: 'Ekota Clinic & Diagnostic Center', district: 'Nilphamari', address: 'জেনারেল হাসপাতাল সড়ক, শান্তিনগর মোড় (কানছিড়ার মোড়), নীলফামারী', doctors: ['ek-med1', 'ek-card1', 'ek-pallab1', 'ek-gyn1', 'ek-med2', 'ek-med3', 'ek-kid1', 'ek-gyn2', 'ek-orth1', 'ek-med4', 'ek-gyn3', 'ek-sur1'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
];

export const EMERGENCY_SERVICES = [
  { id: 'e1', name: 'ECG (ইসিজি)', price: 600, icon: '💓', description: 'বাসায় গিয়ে ইসিজি করা হয়' },
  { id: 'e2', name: 'Blood Collection', price: 200, icon: '🩸', description: 'ল্যাব টেস্টের জন্য রক্ত সংগ্রহ' },
  { id: 'e3', name: 'Nurse Care', price: 1500, icon: '👩‍⚕️', description: 'দক্ষ নার্সিং সেবা (১২ ঘণ্টা)' },
  { id: 'e4', name: 'BP Check', price: 100, icon: '🩺', description: 'ব্লাড প্রেসার ও সুগার চেক' },
];

export const LAB_TESTS: LabTest[] = [];

export const MEDICINES: Medicine[] = [
  { id: 'm1', name: 'Napa Extend', price: 20, discount: 5, image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=200', description: 'Pain relief' },
  { id: 'm2', name: 'Seclo 20', price: 150, discount: 10, image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=200', description: 'Acidity' },
  { id: 'm3', name: 'Fexo 120', price: 90, discount: 0, image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=200', description: 'Allergy' },
];
