
import { Doctor, Clinic, Medicine, LabTest } from './types';

export const DISTRICTS = ['Dhaka', 'Chattogram', 'Sylhet', 'Rajshahi', 'Khulna', 'Barishal', 'Rangpur', 'Mymensingh', 'Nilphamari'];

export const SPECIALTIES = [
  { id: 'medicine', name: 'Medicine', icon: '💊', bnName: 'মেডিসিন' },
  { id: 'cardiology', name: 'Cardiology', icon: '🫀', bnName: 'হৃদরোগ' },
  { id: 'neuromedicine', name: 'Neuromedicine', icon: '🧠', bnName: 'নিউরোলজি' },
  { id: 'gynecology', name: 'Gynecology', icon: '🤰', bnName: 'গাইনী' },
  { id: 'orthopedics', name: 'Orthopedics', icon: '🦴', bnName: 'হাড়-জোড়া' },
  { id: 'pediatrics', name: 'Pediatrics', icon: '👶', bnName: 'শিশু' },
  { id: 'surgery', name: 'Surgery', icon: '🔪', bnName: 'সার্জারি' },
  { id: 'urology', name: 'Urology', icon: '💧', bnName: 'ইউরোলজি' },
  { id: 'endocrinology', name: 'Endocrinology', icon: '🩸', bnName: 'ডায়াবেটিস' },
  { id: 'ent', name: 'ENT', icon: '👂', bnName: 'নাক-কান-গলা' },
  { id: 'dermatology', name: 'Dermatology', icon: '✨', bnName: 'চর্ম-যৌন' },
  { id: 'ophthalmology', name: 'Ophthalmology', icon: '👁️', bnName: 'চক্ষু' },
  { id: 'psychiatry', name: 'Psychiatry', icon: '🧘', bnName: 'মানসিক' },
  { id: 'dentistry', name: 'Dentistry', icon: '🦷', bnName: 'দন্ত' },
  { id: 'gastroenterology', name: 'Gastroenterology', icon: '🧪', bnName: 'পরিপাকতন্ত্র' },
  { id: 'kidney', name: 'Nephrology', icon: '💧', bnName: 'কিডনি' },
  { id: 'cancer', name: 'Oncology', icon: '🧬', bnName: 'ক্যান্সার' },
  { id: 'hematology', name: 'Hematology', icon: '🩸', bnName: 'রক্তরোগ' },
];

export const DOCTORS: Doctor[] = [
  // --- AR General Hospital ---
  { id: 'ar-gyn1', name: 'ডা. মোঃ মনিরুজ্জামান মনি', degree: 'MBBS, BCS (Health), CCD (BIRDEM), MS (Gynae & Obs) | কনসালটেন্ট, ২৫০ শয্যা জেনারেল হাসপাতাল, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ar-uro1', name: 'ডা. মোঃ ময়নুল হক চৌধুরী', degree: 'MBBS, BCS (Health), FCPS (Urology) | সহকারী অধ্যাপক, NICVDU, ঢাকা', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: দুপুর ২:০০ - রাত ৮:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ar-med1', name: 'ডা. মোঃ আশেকুর রহমান', degree: 'MBBS (Dhaka), BCS (Health), FCPS (Medicine), D-CARD (Cardiology), MACP (USA) | কনসালটেন্ট, রংপুর মেডিকেল কলেজ', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ar-card1', name: 'ডা. মোঃ সামিউর রহমান শাহ', degree: 'MBBS, BCS (Health), CCD (BIRDEM), MD (Cardiology), FCPS (Medicine), MACP (USA), FACC (USA) | ইন্টারভেনশনাল কার্ডিওলজিস্ট, জাতীয় হৃদরোগ ইনস্টিটিউট', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ar-orth1', name: 'ডা. রূপায়ন দাশ', degree: 'MBBS, BCS (Health), D-Ortho | কনসালটেন্ট, উপজেলা স্বাস্থ্য কমপ্লেক্স', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: দুপুর ২:০০ - রাত ৮:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ar-psy1', name: 'ডা. দেব দুলাল রায়', degree: 'MBBS, BCS (Health), CCD (BIRDEM), MD (Psychiatry) | BMU ও রংপুর মেডিকেল কলেজ', specialty: 'Psychiatry', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'বৃহস্পতিবার: বিকাল ৪:০০ - রাত ৯:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 1000 },
  { id: 'ar-neuro1', name: 'ডা. মোঃ রুহুল আমিন', degree: 'MBBS, Neurology Specialist | সহযোগী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'মঙ্গলবার: বিকাল ৪:০০ - রাত ৯:০০, শুক্রবার: সকাল ১০:০০ - ১১:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ar-endo1', name: 'ডা. এস.এম. তৌহিদ হাসান', degree: 'MBBS, BCS (Health), DM (Endocrinology), FCPS (Endocrinology), Mayo Clinic Training | BSMMU', specialty: 'Endocrinology', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: সকাল ৯:০০ - দুপুর ২:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'ar-med2', name: 'ডা. মোঃ শামসুর রহমান', degree: 'MBBS, BCS (Health), Medicine Specialist | সহকারী অধ্যাপক', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'রবি, সোম, বুধ: বিকাল ৪:০০ - রাত ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ar-med3', name: 'ডা. মোঃ আব্দুল মতিন', degree: 'MBBS, BCS (Health), Medicine Specialist | সহকারী অধ্যাপক', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শনি-বৃহস্পতি: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Roots Eye Operation & Consultation Center ---
  { id: 'roots-eye1', name: 'ডা. মো. মিজানুর রহমান', degree: 'MBBS, MS (Ophthalmology), BCS (Health) | সহযোগী অধ্যাপক, নীলফামারী মেডিকেল কলেজ', specialty: 'Ophthalmology', districts: ['Nilphamari'], clinics: ['c-roots'], schedule: 'সময়: (যোগাযোগ করুন)', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'roots-eye2', name: 'ডা. মোঃ কামরুল হাসান', degree: 'MBBS (Rajshahi), BCS (Health), MS (Ophthalmology) | কনসালটেন্ট, ২৫০ শয্যা হাসপাতাল', specialty: 'Ophthalmology', districts: ['Nilphamari'], clinics: ['c-roots'], schedule: 'সময়: (যোগাযোগ করুন)', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },

  // --- Ebadot General Hospital ---
  { id: 'ebadot-med1', name: 'ডা. মো. এমদাদুল হক', degree: 'MBBS, Medicine Specialist | কনসালটেন্ট মেডিসিন', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৮:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ebadot-sur1', name: 'ডা. মো. আশরাফুল ইসলাম (আশরাফ)', degree: 'MBBS, BCS (Health), MS (Surgery) | কনসালটেন্ট সার্জারি, ২৫০ শয্যা হাসপাতাল, নীলফামারী', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ebadot-gyn1', name: 'ডা. মোছাঃ জাহানারা খাতুন', degree: 'MBBS, BCS (Health), DGO (Gynae) | কনসালটেন্ট গাইনী, ২৫০ শয্যা হাসপাতাল, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ebadot'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৮:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Moun General Hospital ---
  { id: 'moun-gyn1', name: 'ডা. নিশাত তাবাসসুম', degree: 'MBBS (BUP), PGT, CMU (Ultra), EOC (Gynae) | RMO', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'প্রতিদিন', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'moun-gyn2', name: 'ডা. মাহফুজা আক্তার (লোপা)', degree: 'MBBS, BCS (Health), MS (Gynae & Obs) | কনসালটেন্ট, রংপুর মেডিকেল', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'moun-sur1', name: 'ডা. মোহাম্মদ ওয়াজিবুল্লাহ', degree: 'MBBS, BCS, MRCS, MS (Colorectal Surgery) | সহকারী অধ্যাপক', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'শুক্রবার: সকাল ১১:০০ - বিকাল ৪:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'moun-card1', name: 'ডা. শঙ্কর কুমার সাহা', degree: 'MBBS, D-CARD | সিনিয়র কনসালটেন্ট', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-moun'], schedule: 'সোমবার: ৩:০০ - ৮:০০, শুক্রবার: ১১:০০ - ৪:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },

  // --- Pacific Labzone ---
  { id: 'pacific-gas1', name: 'ডা. মো. হাফিজুল ইসলাম', degree: 'MBBS, MD (Gastroenterology)', specialty: 'Gastroenterology', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'pacific-orth1', name: 'ডা. সৈয়দ হাসান আলী', degree: 'MBBS, MS (Ortho)', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৮:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'pacific-med1', name: 'ডা. মো. শাহজাদা মিয়া', degree: 'MBBS, Medicine Specialist', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'pacific-neuro1', name: 'ডা. আল-আমিন হোসেন', degree: 'MBBS, Medicine & Neuro Specialist', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'pacific-med2', name: 'ডা. মো. আবু তাহের সবুজ', degree: 'MBBS, Medicine Specialist', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'pacific-orth2', name: 'ডা. মো. সারোয়ার হোসেন', degree: 'MBBS, MS (Ortho)', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'pacific-med3', name: 'ডা. মো. রবিউল ইসলাম', degree: 'MBBS, Medicine Specialist', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },

  // --- Madina Diagnostic ---
  { id: 'mad-hema1', name: 'ডা. আব্দুল কাদের জিলানী', degree: 'MBBS, Hematology Specialist', specialty: 'hematology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'শুক্রবার: বিকাল ৪:০০ - রাত ৯:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'mad-card1', name: 'ডা. আরিফুজ্জামান তুহিন', degree: 'MBBS, Cardiology Specialist', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'mad-skin1', name: 'ডা. আব্দুল কুদ্দুস', degree: 'MBBS, Skin/VD Specialist', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৮:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'mad-ent1', name: 'ডা. ধীমান প্রামাণিক', degree: 'MBBS, DLO (ENT)', specialty: 'ENT', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'mad-med1', name: 'ডা. মাসুদ পারভেজ', degree: 'MBBS, Medicine Specialist', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-madina', 'c-janata'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৮:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'mad-orth1', name: 'ডা. আসাদুজ্জামান', degree: 'MBBS, Orthopedic Specialist', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-madina', 'c-greensign'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'mad-gyn1', name: 'ডা. মনিরুজ্জামান', degree: 'MBBS, Gynae Specialist', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'mad-gyn2', name: 'ডাঃ ইফফাত আজিজ (সুমি)', degree: 'MBBS, Gynae Specialist', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'mad-ped1', name: 'ডা. তাবাসসুম মাহজাবিন', degree: 'MBBS, Child Specialist', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Green Sign Hospital ---
  { id: 'gs-gyn1', name: 'ডা. ওবায়দা নাসনীন', degree: 'MBBS, BCS, Gynae Specialist', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'gs-ped1', name: 'ডা. শাহ মোঃ মোয়াজ্জেম হোসেন', degree: 'MBBS, Child Specialist', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ১০:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'gs-orth1', name: 'ডা. আব্দুর রহিম', degree: 'MBBS, Orthopedic Specialist', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-neuro1', name: 'ডা. আসাদুজ্জামান', degree: 'MBBS, MD (Neuro)', specialty: 'Neuromedicine', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'gs-card1', name: 'ডা. আসাদ আলম', degree: 'MBBS, Cardiology Specialist', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-med1', name: 'ডা. মেহফুজ আলী', degree: 'MBBS, Medicine Specialist', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৮:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'gs-gyn2', name: 'ডা. রুমানা আফরোজ', degree: 'MBBS, Gynae Specialist', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'gs-ent1', name: 'ডা. রাশেদুল ইসলাম', degree: 'MBBS, DLO (ENT)', specialty: 'ENT', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'gs-sur1', name: 'ডা. সোহরাব হোসেন', degree: 'MBBS, Surgery Specialist', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-greensign', 'c-janata'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'gs-cancer1', name: 'ডা. আরিফ হাসনাত', degree: 'MBBS, Cancer Specialist', specialty: 'Oncology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 1000 },
  { id: 'gs-skin1', name: 'ডা. ফাহিম কিসওয়ার', degree: 'MBBS, DDV (Skin)', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'gs-med2', name: 'ডা. ইমরান কবীর', degree: 'MBBS, Medicine Specialist', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৮:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'gs-uro1', name: 'ডা. নূরুজ্জামান মিয়া', degree: 'MBBS, MS (Urology)', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },

  // --- Janata Clinic ---
  { id: 'j-gyn1', name: 'ডা. পারুল রানী রায়', degree: 'MBBS, DGO (Gynae)', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: সকাল ১০:০০ - রাত ৮:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-gyn2', name: 'ডা. ফারজানা আক্তার', degree: 'MBBS, Gynae Specialist', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-gyn3', name: 'ডা. আফরোজা খানম', degree: 'MBBS, Gynae Specialist', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: সকাল ১০:০০ - রাত ৮:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'j-sur2', name: 'ডা. আব্দুল্লাহেল মাফী', degree: 'MBBS, MS (Surgery)', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'j-med-t1', name: 'ডা. তাওহীদা নাসরীন', degree: 'MBBS, Medicine Specialist', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-med-a1', name: 'ডা. আতিউর রহমান', degree: 'MBBS, Medicine Specialist', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'j-kid1', name: 'ডা. নীহার রঞ্জন চৌধুরী', degree: 'MBBS, Kidney Specialist', specialty: 'Nephrology', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৮:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'j-ped1', name: 'ডা. কমলাকান্ত রায়', degree: 'MBBS, Child Specialist', specialty: 'Pediatrics', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  { id: 'j-pain1', name: 'ডা. শাহরিয়ার শাকিল', degree: 'MBBS, Pain Specialist', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'j-orth1', name: 'ডা. মোস্তফা আল বানী', degree: 'MBBS, Orthopedic Specialist', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৯:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'j-med-r1', name: 'ডা. ঋতুপর্ণা রায়', degree: 'MBBS, Medicine Specialist', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-janata'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৮:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?auto=format&fit=crop&q=80&w=200', consultationFee: 400 },
  
  // --- New Life Care Diagnostic & Consultation Center ---
  { id: 'nl-med1', name: 'ডা. মোঃ মাসুদ পারভেজ', degree: 'MBBS (SSMC), BCS (Health), MD (Internal Medicine) | রংপুর ও নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'প্রতিদিন: বিকাল ৫:০০ - রাত ৮:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'nl-uro1', name: 'অধ্যাপক ডা. মোহাম্মদ মোবারেক হোসেন', degree: 'MBBS, MS (Urology), FCPS (Surgery) | প্রাক্তন অধ্যাপক, ঢাকা মেডিকেল কলেজ হাসপাতাল', specialty: 'Urology', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 5.0, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 1000 },
  { id: 'nl-gyn1', name: 'ডা. ফারজানা আক্তার', degree: 'MBBS, BCS (Health), CMU, DMU (Ultrasonology) | মেডিকেল অফিসার, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'nl-med2', name: 'ডা. মোঃ ইমরান কবীর', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM), CMU | উপজেলা স্বাস্থ্য ও পরিবার পরিকল্পনা কর্মকর্তা', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ১০:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'nl-card1', name: 'মেহেফুজ আলী', degree: 'MBBS, BCS (Health), FCPS (Medicine), D-CARD (Cardiology) | নীলফামারী সদর হাসপাতাল, নীলফামারী', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'শনি-বৃহস্পতি: দুপুর ২:০০ - রাত ৮:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'nl-skin1', name: 'ডা. ফরহানুল হাসান সিফাত', degree: 'MBBS, PGT (Medicine), D & C (Skin & VD), CCD (BIRDEM) | রংপুর মেডিকেল কলেজ', specialty: 'Dermatology', districts: ['Nilphamari'], clinics: ['c-newlife'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ১০:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },

  // --- Ekota Clinic & Diagnostic Center ---
  { id: 'ek-med1', name: 'ডাঃ দীপ জ্যোতি চক্রবর্তী', degree: 'MBBS (DMC), BCS (Health), FCPS (Medicine), MD (Chest Disease) | ইন্টারভেনশনাল পালমোনলজিস্ট', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি বুধবার: দুপুর ২:০০ - ৫:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ek-card1', name: 'ডাঃ মোঃ হাসানুল ইসলাম', degree: 'MBBS, MD (Cardiology) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ হাসপাতাল', specialty: 'Cardiology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি শুক্রবার: সকাল ৯:০০ - বিকাল ৫:০০', availableToday: false, rating: 5.0, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ek-pallab1', name: 'ডাঃ পল্লব কুমার দাস', degree: 'MBBS (SULT), M.Phil | সহযোগী অধ্যাপক, এম আব্দুর রহিম মেডিকেল কলেজ, দিনাজপুর', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি শুক্রবার: সকাল ১০:০০ - দুপুর ২:০০', availableToday: false, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 700 },
  { id: 'ek-gyn1', name: 'ডাঃ আবু হেনা মোস্তফা কামাল', degree: 'MBBS, BCS (Health), FCPS (Part-2), CMU | মেডিকেল অফিসার, পার্বতীপুর', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি বৃহস্পতিবার: বিকাল ৪:০০ - রাত ৯:০০', availableToday: false, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ek-med2', name: 'ডাঃ মোঃ মাহবুব-উল-আলম', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM) | মেডিকেল অফিসার, ২৫০ শয্যা হাসপাতাল, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: বিকাল ৪:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-med3', name: 'ডাঃ এস এম জাওয়াদুল হক', degree: 'MBBS, VTCD (Chest), PGT (Medicine) | সহকারী অধ্যাপক, রংপুর মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: দুপুর ১:০০ - রাত ৮:০০ (শুক্রবন্ধ)', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ek-kid1', name: 'ডাঃ নীহা রঞ্জন চৌধুরী', degree: 'MBBS, BCS (Health), PGT (Medicine), CCD (BIRDEM) | মেডিকেল অফিসার, ২৫০ শয্যা হাসপাতাল, নীলফামারী', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: দুপুর ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.7, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-gyn2', name: 'ডাঃ মাকছুরা খানম মাতুল চৌধুরী', degree: 'MBBS (RU), CMU-Ultra (Dhaka) | প্রাক্তন আবাসিক মেডিকেল অফিসার', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'শনি-বৃহস্পতি: সকাল ১০:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1559839734-2b71f1536780?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-orth1', name: 'ডাঃ এইচ.এম. সাদী (সানি)', degree: 'MBBS, BCS (Health), MS (Ortho Course), NITOR (Pangu Hospital), FCPS (FP), CMU, CCD | ট্রমা এন্ড অর্থো সার্জন (BMDC: ৭৭৬৬০)', specialty: 'Orthopedics', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতি শুক্রবার: সকাল ১০:০০ - রাত ৮:০০', availableToday: false, rating: 4.9, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 800 },
  { id: 'ek-med4', name: 'ডাঃ মোঃ মাসুদ পারভেজ', degree: 'MBBS (SSMC), BCS (Health), MD (Internal Medicine) | নীলফামারী মেডিকেল কলেজ', specialty: 'Medicine', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ১০:০০', availableToday: true, rating: 4.9, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
  { id: 'ek-gyn3', name: 'ডাঃ ফারজানা আক্তার', degree: 'MBBS, BCS (Health), CMU, DMU | মেডিকেল অফিসার, নীলফামারী', specialty: 'Gynecology', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: দুপুর ২:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1623854767233-2d2c322cc4e2?auto=format&fit=crop&q=80&w=200', consultationFee: 500 },
  { id: 'ek-sur1', name: 'ডাঃ এম এ সুজন', degree: 'MBBS (Raj), BCS (Health), CMU, PGT (Surgery) | মেডিকেল অফিসার, নীলফামারী মেডিকেল কলেজ', specialty: 'Surgery', districts: ['Nilphamari'], clinics: ['c-ekota'], schedule: 'প্রতিদিন: বিকাল ৩:০০ - রাত ৯:০০', availableToday: true, rating: 4.8, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200', consultationFee: 600 },
];

export const CLINICS: Clinic[] = [
  { id: 'c-madina', name: 'Madina Diagnostic Clinic & Consultation', district: 'Nilphamari', address: 'জেনারেল হাসপাতাল রোড, হাসপাতাল মোড়, নীলফামারী', doctors: ['mad-hema1', 'mad-card1', 'mad-skin1', 'mad-ent1', 'mad-med1', 'mad-orth1', 'mad-gyn1', 'mad-gyn2', 'mad-ped1'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-greensign', name: 'Green Sign Hospital & Diagnostic Lab', district: 'Nilphamari', address: 'নীলফামারী সদর', doctors: ['gs-gyn1', 'gs-ped1', 'gs-orth1', 'gs-neuro1', 'gs-card1', 'gs-med1', 'gs-gyn2', 'gs-ent1', 'gs-sur1', 'gs-cancer1', 'gs-skin1', 'gs-med2', 'gs-uro1'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ar', name: 'AR General Hospital', district: 'Nilphamari', address: 'সদর হাসপাতাল রোড, নীলফামারী', doctors: ['ar-gyn1', 'ar-uro1', 'ar-med1', 'ar-card1', 'ar-orth1', 'ar-psy1', 'ar-neuro1', 'ar-endo1', 'ar-med2', 'ar-med3'], image: 'https://images.unsplash.com/photo-1587350859728-117699f8aee1?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-janata', name: 'Janata Clinic & Diagnostic Center', district: 'Nilphamari', address: 'হাসপাতাল রোড, শান্তিনগর মোড়, নীলফামারী সদর', doctors: ['j-gyn1', 'j-gyn2', 'j-gyn3', 'gs-sur1', 'j-sur2', 'mad-med1', 'j-med-t1', 'j-med-a1', 'j-kid1', 'j-ped1', 'j-pain1', 'j-orth1', 'j-med-r1'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-roots', name: 'Roots Eye Operation & Consultation Center', district: 'Nilphamari', address: 'নীলফামারী সদর', doctors: ['roots-eye1', 'roots-eye2'], image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-moun', name: 'Moun General Hospital & Diagnostic Center', district: 'Nilphamari', address: 'নীলফামারী সদর', doctors: ['moun-gyn1', 'moun-gyn2', 'moun-sur1', 'moun-card1'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-pacific', name: 'Pacific Labzone', district: 'Nilphamari', address: 'নীলফামারী', doctors: ['pacific-gas1', 'pacific-orth1', 'pacific-med1', 'pacific-neuro1', 'pacific-med2', 'pacific-orth2', 'pacific-med3'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ebadot', name: 'Ebadot General Hospital & Digital Diagnostic Center', district: 'Nilphamari', address: 'কলেজ রোড, নীলফামারী সদর', doctors: ['ebadot-med1', 'ebadot-sur1', 'ebadot-gyn1'], image: 'https://images.unsplash.com/photo-1587350859728-117699f8aee1?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-newlife', name: 'New Life Care Diagnostic & Consultation Center', district: 'Nilphamari', address: 'চৌরঙ্গী মোড় (হাসপাতাল সড়ক), পোস্ট অফিস সংলগ্ন, নার্সিং কলেজের সামনে, নীলফামারী', doctors: ['nl-med1', 'nl-uro1', 'nl-gyn1', 'nl-med2', 'nl-card1', 'nl-skin1'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ekota', name: 'Ekota Clinic & Diagnostic Center', district: 'Nilphamari', address: 'জেনারেল হাসপাতাল সড়ক, শান্তিনগর মোড় (কানছিড়ার মোড়), নীলফামারী', doctors: ['ek-med1', 'ek-card1', 'ek-pallab1', 'ek-gyn1', 'ek-med2', 'ek-med3', 'ek-kid1', 'ek-gyn2', 'ek-orth1', 'ek-med4', 'ek-gyn3', 'ek-sur1'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
];

export const EMERGENCY_SERVICES = [
  { id: 'e1', name: 'ECG (ইসিজি)', price: 600, icon: '💓', description: 'বাসায় গিয়ে ইসিজি করা হয়' },
  { id: 'e2', name: 'Blood Collection', price: 200, icon: '🩸', description: 'ল্যাব টেস্টের জন্য রক্ত সংগ্রহ' },
  { id: 'e3', name: 'Nurse Care', price: 1500, icon: '👩‍⚕️', description: 'দক্ষ নার্সিং সেবা (১২ ঘণ্টা)' },
  { id: 'e4', name: 'BP Check', price: 100, icon: '🩺', description: 'ব্লাড প্রেসার ও সুগার চেক' },
];

export const LAB_TESTS: LabTest[] = [
  { id: 'lt1', name: 'RBS (রক্তের সুগার)', price: 200 },
  { id: 'lt2', name: 'FBS & 2HRS', price: 400 },
  { id: 'lt3', name: 'S.Creatinine (কিডনি)', price: 500 },
  { id: 'lt4', name: 'CBC (রক্ত পরীক্ষা)', price: 600 },
  { id: 'lt5', name: 'SGPT (লিভার)', price: 500 },
  { id: 'lt6', name: 'SGOT', price: 600 },
  { id: 'lt31', name: 'Troponin- I (হার্ট অ্যাটাক)', price: 1500 },
  { id: 'lt40', name: 'TSH (থাইরয়েড)', price: 1000 },
  { id: 'lt48', name: 'HBA1C (ডায়াবেটিস ৩ মাস)', price: 1200 },
  { id: 'lt73', name: 'USG Whole Abdomen', price: 750 },
  { id: 'lt79', name: 'ECG (ইসিজি)', price: 600 },
  { id: 'lt82', name: 'X-Ray Chest', price: 600 },
];

export const MEDICINES: Medicine[] = [
  { id: 'm1', name: 'Napa Extend', price: 20, discount: 5, image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=200', description: 'Pain relief' },
  { id: 'm2', name: 'Seclo 20', price: 150, discount: 10, image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=200', description: 'Acidity' },
  { id: 'm3', name: 'Fexo 120', price: 90, discount: 0, image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=200', description: 'Allergy' },
];
